Program 0x00
Spawn "e_50"

Program 0x01
Party W_FRIEND_FIX
AreaSettings 0 -1
	SetProgressFlag 0x2034
	SetEvent "106" Type 2
	SetJump Type 2 World MU Area 0 Entrance 0 LocalSet 71 FadeType 1
	SetPartyMenu 0

Spawn "e_10"
Spawn "e_50"

Program 0x47
Bgm 112 112
AreaSettings 1 -1
	SetProgressFlag 0x2035
	SetEvent "107" Type 4
	SetJump Type 1 World MU Area 4 Entrance 0 LocalSet 0 FadeType 1
	SetPartyMenu 0
