Program 0x00
Spawn "e_50"

Program 0x01
Party W_FRIEND_FIX
AreaSettings 9 -1
	SetProgressFlag 0x2037
	SetUnk05 0x1
	SetEvent "109" Type 1
	SetJump Type 2 World MU Area 0 Entrance 0 LocalSet 72 FadeType 1
	SetPartyMenu 0

Spawn "e_10"
Spawn "e_50"

Program 0x48
Bgm 131 131
AreaSettings 7 -1
	SetProgressFlag 0x2038
	SetMember 4
	SetUnk05 0x3
	SetEvent "110" Type 8
	SetJump Type 1 World MU Area 5 Entrance 50 LocalSet 0 FadeType 1
	SetPartyMenu 0
