Program 0x14F
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_99"

Program 0x1D
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_99"

Program 0x75
MapVisibility 0x000003bf 0x00000000
Spawn "m_71"

Program 0x00
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_99"

Program 0x147
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_99"

Program 0x125
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_99"

Program 0x01
Unk0e 1
MapVisibility 0x000003bf 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_21"
Spawn "m_70"
Spawn "m_80"
Spawn "m_81"

Program 0x02
Unk0e 1
MapVisibility 0x000003bf 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_21"
Spawn "m_70"
Spawn "m_80"
Spawn "m_81"
Spawn "m_83"
Spawn "m_96"
Spawn "m_98"

Program 0x03
Unk0e 0
MapVisibility 0x0000001f 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_21"
Spawn "m_70"
Spawn "m_80"

Program 0x77
MapVisibility 0x0000001f 0x00000000
Spawn "m_71"

Program 0x04
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_21"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"

Program 0x05
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_01"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_21"
SpawnAlt "m_22"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"

Program 0x06
Unk0e 0
MapVisibility 0x0000001f 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_97"

Program 0x76
MapVisibility 0x000003ff 0x00000000
Spawn "m_71"

Program 0x1A
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_20"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"

Program 0x07
Unk0e 0
MapVisibility 0x0000039f 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_97"

Program 0x14D
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_99"

Program 0xFB
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_99"

Program 0x164
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_99"

Program 0x14E
Unk0e 2
MapVisibility 0x000003ff 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_13"
Spawn "m_14"
Spawn "m_20"
Spawn "m_71"
Spawn "m_80"
Spawn "m_81"
Spawn "m_82"
Spawn "m_84"
Spawn "m_94"
Spawn "m_95"
Spawn "m_99"

Program 0x1C
Unk0e 1
MapVisibility 0x000003bf 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_12"
Spawn "m_21"
Spawn "m_70"
Spawn "m_80"
Spawn "m_81"
Spawn "m_96"
Spawn "m_98"