from itemClass import KH2Item

itemList = [
    KH2Item(593, "Proof of Connection", "Proof"),
    KH2Item(594, "Proof of Nonexistence", "Proof"),
    KH2Item(595, "Proof of Peace", "Proof"),

    KH2Item(21, "Fire Element", "Fire"),
    KH2Item(21, "Fire Element", "Fire"),
    KH2Item(21, "Fire Element", "Fire"),

    KH2Item(22, "Blizzard Element", "Blizzard"),
    KH2Item(22, "Blizzard Element", "Blizzard"),
    KH2Item(22, "Blizzard Element", "Blizzard"),

    KH2Item(23, "Thunder Element", "Thunder"),
    KH2Item(23, "Thunder Element", "Thunder"),
    KH2Item(23, "Thunder Element", "Thunder"),

    KH2Item(24, "Cure Element", "Cure"),
    KH2Item(24, "Cure Element", "Cure"),
    KH2Item(24, "Cure Element", "Cure"),

    KH2Item(87, "Magnet Element", "Magnet"),
    KH2Item(87, "Magnet Element", "Magnet"),
    KH2Item(87, "Magnet Element", "Magnet"),

    KH2Item(88, "Reflect Element", "Reflect"),
    KH2Item(88, "Reflect Element", "Reflect"),
    KH2Item(88, "Reflect Element", "Reflect"),

    KH2Item(94, "High Jump","GrowthAbility"),
    KH2Item(95, "High Jump","GrowthAbility"),
    KH2Item(96, "High Jump","GrowthAbility"),
    KH2Item(97, "High Jump","GrowthAbility"),

    KH2Item(98, "Quick Run","GrowthAbility"),
    KH2Item(99, "Quick Run","GrowthAbility"),
    KH2Item(100, "Quick Run","GrowthAbility"),
    KH2Item(101, "Quick Run","GrowthAbility"),

    KH2Item(102, "Aerial Dodge","GrowthAbility"),
    KH2Item(103, "Aerial Dodge","GrowthAbility"),
    KH2Item(104, "Aerial Dodge","GrowthAbility"),
    KH2Item(105, "Aerial Dodge","GrowthAbility"),

    KH2Item(106, "Glide","GrowthAbility"),
    KH2Item(107, "Glide","GrowthAbility"),
    KH2Item(108, "Glide","GrowthAbility"),
    KH2Item(109, "Glide","GrowthAbility"),

    KH2Item(564, "Dodge Roll","GrowthAbility"),
    KH2Item(565, "Dodge Roll","GrowthAbility"),
    KH2Item(567, "Dodge Roll","GrowthAbility"),
    KH2Item(568, "Dodge Roll","GrowthAbility"),

    KH2Item(32, "Torn Pages","TornPage"),
    KH2Item(32, "Torn Pages","TornPage"),
    KH2Item(32, "Torn Pages","TornPage"),
    KH2Item(32, "Torn Pages","TornPage"),
    KH2Item(32, "Torn Pages","TornPage"),
]

supportAbilityList = [
    KH2Item(138,"Scan","SupportAbility"),
    KH2Item(138,"Scan","SupportAbility"),
    KH2Item(158,"Aerial Recovery","SupportAbility"),
    KH2Item(539,"Combo Master","SupportAbility"),
    KH2Item(162,"Combo Plus","SupportAbility"),
    KH2Item(162,"Combo Plus","SupportAbility"),
    KH2Item(162,"Combo Plus","SupportAbility"),
    KH2Item(163,"Air Combo Plus","SupportAbility"),
    KH2Item(163,"Air Combo Plus","SupportAbility"),
    KH2Item(163,"Air Combo Plus","SupportAbility"),
    KH2Item(390,"Combo Boost","SupportAbility"),
    KH2Item(390,"Combo Boost","SupportAbility"),
    KH2Item(391,"Air Combo Boost","SupportAbility"),
    KH2Item(391,"Air Combo Boost","SupportAbility"),
    KH2Item(392,"Reaction Boost","SupportAbility"),
    KH2Item(392,"Reaction Boost","SupportAbility"),
    KH2Item(392,"Reaction Boost","SupportAbility"),
    KH2Item(393,"Finishing Plus","SupportAbility"),
    KH2Item(393,"Finishing Plus","SupportAbility"),
    KH2Item(393,"Finishing Plus","SupportAbility"),
    KH2Item(394,"Negative Combo","SupportAbility"),
    KH2Item(394,"Negative Combo","SupportAbility"),
    KH2Item(395,"Berserk Charge","SupportAbility"),
    KH2Item(395,"Berserk Charge","SupportAbility"),
    KH2Item(396,"Damage Drive","SupportAbility"),
    KH2Item(397,"Drive Boost","SupportAbility"),
    KH2Item(397,"Drive Boost","SupportAbility"),
    KH2Item(398,"Form Boost","SupportAbility"),
    KH2Item(398,"Form Boost","SupportAbility"),
    KH2Item(398,"Form Boost","SupportAbility"),
    KH2Item(399,"Summon Boost","SupportAbility"),
    KH2Item(400,"Combination Boost","SupportAbility"),
    KH2Item(401,"Experience Boost","SupportAbility"),
    KH2Item(401,"Experience Boost","SupportAbility"),
    KH2Item(402,"Leaf Bracer","SupportAbility"),
    KH2Item(403,"Magic Lock-On","SupportAbility"),
    KH2Item(405,"Draw","SupportAbility"),
    KH2Item(405,"Draw","SupportAbility"),
    KH2Item(405,"Draw","SupportAbility"),
    KH2Item(405,"Draw","SupportAbility"),
    KH2Item(406,"Jackpot","SupportAbility"),
    KH2Item(406,"Jackpot","SupportAbility"),
    KH2Item(407,"Lucky Lucky","SupportAbility"),
    KH2Item(407,"Lucky Lucky","SupportAbility"),
    KH2Item(407,"Lucky Lucky","SupportAbility"),
    KH2Item(540,"Drive Converter","SupportAbility"),
    KH2Item(540,"Drive Converter","SupportAbility"),
    KH2Item(408,"Fire Boost","SupportAbility"),
    KH2Item(408,"Fire Boost","SupportAbility"),
    KH2Item(409,"Blizzard Boost","SupportAbility"),
    KH2Item(409,"Blizzard Boost","SupportAbility"),
    KH2Item(410,"Thunder Boost","SupportAbility"),
    KH2Item(410,"Thunder Boost","SupportAbility"),
    KH2Item(411,"Item Boost","SupportAbility"),
    KH2Item(411,"Item Boost","SupportAbility"),
    KH2Item(412,"MP Rage","SupportAbility"),
    KH2Item(412,"MP Rage","SupportAbility"),
    KH2Item(413,"MP Haste","SupportAbility"),
    KH2Item(413,"MP Haste","SupportAbility"),
    KH2Item(421,"MP Hastera","SupportAbility"),
    KH2Item(421,"MP Hastera","SupportAbility"),
    KH2Item(422,"MP Hastega","SupportAbility"),
    KH2Item(414,"Defender","SupportAbility"),
    KH2Item(414,"Defender","SupportAbility"),
    KH2Item(542,"Damage Control","SupportAbility"),
    KH2Item(542,"Damage Control","SupportAbility"),
    KH2Item(415,"Second Chance","SupportAbility"),
    KH2Item(416,"Once More","SupportAbility"),
    KH2Item(404,"No Experience","SupportAbility"),
    KH2Item(404,"No Experience","SupportAbility"),
    KH2Item(541,"Light & Darkness","SupportAbility"),


]

actionAbilityList = [
    KH2Item(82, "Guard", "ActionAbility"),
    KH2Item(137, "Upper Slash", "ActionAbility"),
    KH2Item(271, "Horizontal Slash", "ActionAbility"),
    KH2Item(267, "Finishing Leap", "ActionAbility"),
    KH2Item(273, "Relatliating Slash", "ActionAbility"),
    KH2Item(262, "Slapshot", "ActionAbility"),
    KH2Item(263, "Dodge Slash", "ActionAbility"),
    KH2Item(559, "Flash Step", "ActionAbility"),
    KH2Item(264, "Slide Dash", "ActionAbility"),
    KH2Item(562, "Vicinity Break", "ActionAbility"),
    KH2Item(265, "Guard Break", "ActionAbility"),
    KH2Item(266, "Explosion", "ActionAbility"),
    KH2Item(269, "Aerial Sweep", "ActionAbility"),
    KH2Item(560, "Aerial Dive", "ActionAbility"),
    KH2Item(270, "Aerial Spiral", "ActionAbility"),
    KH2Item(272, "Aerial Finish", "ActionAbility"),
    KH2Item(561, "Magnet Burst", "ActionAbility"),
    KH2Item(268, "Counterguard", "ActionAbility"),
    KH2Item(385, "Auto Valor", "ActionAbility"),
    KH2Item(386, "Auto Wisdom", "ActionAbility"),
    KH2Item(387, "Auto Master", "ActionAbility"),
    KH2Item(388, "Auto Final", "ActionAbility"),
    KH2Item(389, "Auto Summon", "ActionAbility"),
    KH2Item(568, "Auto Limit", "ActionAbility"),
    KH2Item(198, "Trinity Limit", "ActionAbility"),

]

junkList = [
    KH2Item(576, "Remembrance Shard", "Junk"),
    KH2Item(577, "Remembrance Stone", "Junk"),
    KH2Item(578, "Remembrance Gem", "Junk"),
    KH2Item(584, "Lost Illusion", "Junk"),
    KH2Item(585, "Manifest Illusion", "Junk"),
    KH2Item(345, "Mythril Shard", "Junk"),
    KH2Item(346, "Mythril Stone", "Junk"),
    KH2Item(347, "Mythril Gem", "Junk"),
    KH2Item(348, "Mythril Crystal", "Junk"),
    KH2Item(349,"Bright Shard", "Junk"),
]

donaldItems = []

goofyItems = []