from itemClass import KH2Item

itemList = [
    KH2Item(593, "Proof of Connection", "ProofofConnection"),
    KH2Item(594, "Proof of Nonexistence", "Proof"),
    KH2Item(595, "Proof of Peace", "ProofofPeace"),

    KH2Item(21, "Fire Element", "Fire"),
    KH2Item(21, "Fire Element", "Fire"),
    KH2Item(21, "Fire Element", "Fire"),

    KH2Item(22, "Blizzard Element", "Blizzard"),
    KH2Item(22, "Blizzard Element", "Blizzard"),
    KH2Item(22, "Blizzard Element", "Blizzard"),

    KH2Item(23, "Thunder Element", "Thunder"),
    KH2Item(23, "Thunder Element", "Thunder"),
    KH2Item(23, "Thunder Element", "Thunder"),

    KH2Item(24, "Cure Element", "Cure"),
    KH2Item(24, "Cure Element", "Cure"),
    KH2Item(24, "Cure Element", "Cure"),

    KH2Item(87, "Magnet Element", "Magnet"),
    KH2Item(87, "Magnet Element", "Magnet"),
    KH2Item(87, "Magnet Element", "Magnet"),

    KH2Item(88, "Reflect Element", "Reflect"),
    KH2Item(88, "Reflect Element", "Reflect"),
    KH2Item(88, "Reflect Element", "Reflect"),

    KH2Item(94, "High Jump","GrowthAbility"),
    KH2Item(95, "High Jump","GrowthAbility"),
    KH2Item(96, "High Jump","GrowthAbility"),
    KH2Item(97, "High Jump","GrowthAbility"),

    KH2Item(98, "Quick Run","GrowthAbility"),
    KH2Item(99, "Quick Run","GrowthAbility"),
    KH2Item(100, "Quick Run","GrowthAbility"),
    KH2Item(101, "Quick Run","GrowthAbility"),

    KH2Item(102, "Aerial Dodge","GrowthAbility"),
    KH2Item(103, "Aerial Dodge","GrowthAbility"),
    KH2Item(104, "Aerial Dodge","GrowthAbility"),
    KH2Item(105, "Aerial Dodge","GrowthAbility"),

    KH2Item(106, "Glide","GrowthAbility"),
    KH2Item(107, "Glide","GrowthAbility"),
    KH2Item(108, "Glide","GrowthAbility"),
    KH2Item(109, "Glide","GrowthAbility"),

    KH2Item(564, "Dodge Roll","GrowthAbility"),
    KH2Item(565, "Dodge Roll","GrowthAbility"),
    KH2Item(567, "Dodge Roll","GrowthAbility"),
    KH2Item(568, "Dodge Roll","GrowthAbility"),

    KH2Item(32, "Torn Pages","TornPage"),
    KH2Item(32, "Torn Pages","TornPage"),
    KH2Item(32, "Torn Pages","TornPage"),
    KH2Item(32, "Torn Pages","TornPage"),
    KH2Item(32, "Torn Pages","TornPage"),

    KH2Item(159, "Lamp Charm (Genie)","Summon"),
    KH2Item(160, "Feather Charm (Peter Pan)", "Summon"),
    KH2Item(25, "Ukulele Charm (Stitch)", "Summon"),
    KH2Item(383, "Baseball Charm (Chicken Little)", "Summon"),

    KH2Item(226, "Secret Ansem's Report 1", "Report"),
    KH2Item(227, "Secret Ansem's Report 2", "Report"),
    KH2Item(228, "Secret Ansem's Report 3", "Report"),
    KH2Item(229, "Secret Ansem's Report 4", "Report"),
    KH2Item(230, "Secret Ansem's Report 5", "Report"),
    KH2Item(231, "Secret Ansem's Report 6", "Report"),
    KH2Item(232, "Secret Ansem's Report 7", "Report"),
    KH2Item(233, "Secret Ansem's Report 8", "Report"),
    KH2Item(234, "Secret Ansem's Report 9", "Report"),
    KH2Item(235, "Secret Ansem's Report 10", "Report"),
    KH2Item(236, "Secret Ansem's Report 11", "Report"),
    KH2Item(237, "Secret Ansem's Report 12", "Report"),
    KH2Item(238, "Secret Ansem's Report 13", "Report"),

    KH2Item(42,"Oathkeeper", "Keyblade"),
    KH2Item(43,"Oblivion","Keyblade"),
    KH2Item(484,"Hero's Crest","Keyblade"),
    KH2Item(485,"Monochrome","Keyblade"),
    KH2Item(486,"Follow the Wind","Keyblade"),
    KH2Item(487,"Circle of Life","Keyblade"),
    KH2Item(488,"Photon Debugger","Keyblade"),
    KH2Item(489,"Gull Wing","Keyblade"),
    KH2Item(490,"Rumbling Rose","Keyblade"),
    KH2Item(491,"Guardian Soul","Keyblade"),
    KH2Item(492,"Wishing Lamp","Keyblade"),
    KH2Item(493,"Decisive Pumpkin","Keyblade"),
    KH2Item(494,"Sleeping Lion","Keyblade"),
    KH2Item(495,"Sweet Memories","Keyblade"),
    KH2Item(496,"Mysterious Abyss","Keyblade"),
    KH2Item(497,"Fatal Crest","Keyblade"),
    KH2Item(498,"Bond of Flame","Keyblade"),
    KH2Item(499,"Fenrir","Keyblade"),
    KH2Item(500,"Ultima Weapon","Keyblade"),

    KH2Item(546, "Centurion+", "Staff"), #StatEntry = 151
    KH2Item(151, "Comet Staff", "Staff"), #StatEntry = 90
    KH2Item(148, "Hammer Staff", "Staff"), #StatEntry = 87
    KH2Item(152, "Lord's Broom", "Staff"), #StatEntry = 91
    KH2Item(75, "Mage's Staff", "Staff"), #StatEntry = 86
    KH2Item(150, "Meteor Staff", "Staff"), #StatEntry = 89
    KH2Item(155, "Nobody Lance", "Staff"), #StatEntry = 94
    KH2Item(549, "Precious Mushroom", "Staff"), #StatEntry = 154
    KH2Item(550, "Precious Mushroom+", "Staff"), #StatEntry = 155
    KH2Item(551, "Premium Mushroom", "Staff"), #StatEntry = 156
    KH2Item(154, "Rising Dragon", "Staff"), #StatEntry = 93
    KH2Item(503, "Save The Queen+", "Staff"), #StatEntry = 146
    KH2Item(156, "Shaman's Relic", "Staff"), #StatEntry = 95
    KH2Item(149, "Victory Bell", "Staff"), #StatEntry = 88
    KH2Item(153, "Wisdom Wand", "Staff"), #StatEntry = 92

    KH2Item(535,"Munny Pouch","MunnyPouch"),
    KH2Item(362, "Munny Pouch","MunnyPouch"),

    KH2Item(1, "Potion","Item"),
    KH2Item(2, "Hi-Potion","Item"),
    KH2Item(3, "Ether", "Item"),
    KH2Item(4, "Elixir", "Item"),
    KH2Item(5,"Mega-Potion","Item"),
    KH2Item(6,"Mega-Ether","Item"),
    KH2Item(7,"Megalixir","Item"),



]

supportAbilityList = [
    KH2Item(138,"Scan","SupportAbility"),
    KH2Item(138,"Scan","SupportAbility"),
    KH2Item(158,"Aerial Recovery","SupportAbility"),
    KH2Item(539,"Combo Master","SupportAbility"),
    KH2Item(162,"Combo Plus","SupportAbility"),
    KH2Item(162,"Combo Plus","SupportAbility"),
    KH2Item(162,"Combo Plus","SupportAbility"),
    KH2Item(163,"Air Combo Plus","SupportAbility"),
    KH2Item(163,"Air Combo Plus","SupportAbility"),
    KH2Item(163,"Air Combo Plus","SupportAbility"),
    KH2Item(390,"Combo Boost","SupportAbility"),
    KH2Item(390,"Combo Boost","SupportAbility"),
    KH2Item(391,"Air Combo Boost","SupportAbility"),
    KH2Item(391,"Air Combo Boost","SupportAbility"),
    KH2Item(392,"Reaction Boost","SupportAbility"),
    KH2Item(392,"Reaction Boost","SupportAbility"),
    KH2Item(392,"Reaction Boost","SupportAbility"),
    KH2Item(393,"Finishing Plus","SupportAbility"),
    KH2Item(393,"Finishing Plus","SupportAbility"),
    KH2Item(393,"Finishing Plus","SupportAbility"),
    KH2Item(394,"Negative Combo","SupportAbility"),
    KH2Item(394,"Negative Combo","SupportAbility"),
    KH2Item(395,"Berserk Charge","SupportAbility"),
    KH2Item(395,"Berserk Charge","SupportAbility"),
    KH2Item(396,"Damage Drive","SupportAbility"),
    KH2Item(397,"Drive Boost","SupportAbility"),
    KH2Item(397,"Drive Boost","SupportAbility"),
    KH2Item(398,"Form Boost","SupportAbility"),
    KH2Item(398,"Form Boost","SupportAbility"),
    KH2Item(398,"Form Boost","SupportAbility"),
    KH2Item(399,"Summon Boost","SupportAbility"),
    KH2Item(400,"Combination Boost","SupportAbility"),
    KH2Item(401,"Experience Boost","SupportAbility"),
    KH2Item(401,"Experience Boost","SupportAbility"),
    KH2Item(402,"Leaf Bracer","SupportAbility"),
    KH2Item(403,"Magic Lock-On","SupportAbility"),
    KH2Item(405,"Draw","SupportAbility"),
    KH2Item(405,"Draw","SupportAbility"),
    KH2Item(405,"Draw","SupportAbility"),
    KH2Item(405,"Draw","SupportAbility"),
    KH2Item(406,"Jackpot","SupportAbility"),
    KH2Item(406,"Jackpot","SupportAbility"),
    KH2Item(407,"Lucky Lucky","SupportAbility"),
    KH2Item(407,"Lucky Lucky","SupportAbility"),
    KH2Item(407,"Lucky Lucky","SupportAbility"),
    KH2Item(540,"Drive Converter","SupportAbility"),
    KH2Item(540,"Drive Converter","SupportAbility"),
    KH2Item(408,"Fire Boost","SupportAbility"),
    KH2Item(408,"Fire Boost","SupportAbility"),
    KH2Item(409,"Blizzard Boost","SupportAbility"),
    KH2Item(409,"Blizzard Boost","SupportAbility"),
    KH2Item(410,"Thunder Boost","SupportAbility"),
    KH2Item(410,"Thunder Boost","SupportAbility"),
    KH2Item(411,"Item Boost","SupportAbility"),
    KH2Item(411,"Item Boost","SupportAbility"),
    KH2Item(412,"MP Rage","SupportAbility"),
    KH2Item(412,"MP Rage","SupportAbility"),
    KH2Item(413,"MP Haste","SupportAbility"),
    KH2Item(413,"MP Haste","SupportAbility"),
    KH2Item(421,"MP Hastera","SupportAbility"),
    KH2Item(421,"MP Hastera","SupportAbility"),
    KH2Item(422,"MP Hastega","SupportAbility"),
    KH2Item(414,"Defender","SupportAbility"),
    KH2Item(414,"Defender","SupportAbility"),
    KH2Item(542,"Damage Control","SupportAbility"),
    KH2Item(542,"Damage Control","SupportAbility"),
    KH2Item(415,"Second Chance","SupportAbility"),
    KH2Item(416,"Once More","SupportAbility"),
    KH2Item(404,"No Experience","SupportAbility"),
    KH2Item(404,"No Experience","SupportAbility"),
    KH2Item(541,"Light & Darkness","SupportAbility"),


]

actionAbilityList = [
    KH2Item(82, "Guard", "ActionAbility"),
    KH2Item(137, "Upper Slash", "ActionAbility"),
    KH2Item(271, "Horizontal Slash", "ActionAbility"),
    KH2Item(267, "Finishing Leap", "ActionAbility"),
    KH2Item(273, "Relatliating Slash", "ActionAbility"),
    KH2Item(262, "Slapshot", "ActionAbility"),
    KH2Item(263, "Dodge Slash", "ActionAbility"),
    KH2Item(559, "Flash Step", "ActionAbility"),
    KH2Item(264, "Slide Dash", "ActionAbility"),
    KH2Item(562, "Vicinity Break", "ActionAbility"),
    KH2Item(265, "Guard Break", "ActionAbility"),
    KH2Item(266, "Explosion", "ActionAbility"),
    KH2Item(269, "Aerial Sweep", "ActionAbility"),
    KH2Item(560, "Aerial Dive", "ActionAbility"),
    KH2Item(270, "Aerial Spiral", "ActionAbility"),
    KH2Item(272, "Aerial Finish", "ActionAbility"),
    KH2Item(561, "Magnet Burst", "ActionAbility"),
    KH2Item(268, "Counterguard", "ActionAbility"),
    KH2Item(385, "Auto Valor", "ActionAbility"),
    KH2Item(386, "Auto Wisdom", "ActionAbility"),
    KH2Item(387, "Auto Master", "ActionAbility"),
    KH2Item(388, "Auto Final", "ActionAbility"),
    KH2Item(389, "Auto Summon", "ActionAbility"),
    KH2Item(568, "Auto Limit", "ActionAbility"),
    KH2Item(198, "Trinity Limit", "ActionAbility"),

]

junkList = [
    KH2Item(576, "Remembrance Shard", "Junk"),
    KH2Item(577, "Remembrance Stone", "Junk"),
    KH2Item(578, "Remembrance Gem", "Junk"),
    KH2Item(584, "Lost Illusion", "Junk"),
    KH2Item(585, "Manifest Illusion", "Junk"),
    KH2Item(345, "Mythril Shard", "Junk"),
    KH2Item(346, "Mythril Stone", "Junk"),
    KH2Item(347, "Mythril Gem", "Junk"),
    KH2Item(348, "Mythril Crystal", "Junk"),
    KH2Item(349, "Bright Shard", "Junk"),
]

donaldAbilityList = [
    KH2Item(165, "Donald Fire", "DonaldAbility"),
    KH2Item(166, "Donald Blizzard", "DonaldAbility"),
    KH2Item(167, "Donald Thunder", "DonaldAbility"),
    KH2Item(168, "Donald Cure", "DonaldAbility"),
    KH2Item(199, "Fantasia", "DonaldAbility"),
    KH2Item(200, "Flare Force", "DonaldAbility"),
    KH2Item(405, "Draw", "DonaldAbility"),
    KH2Item(406, "Jackpot", "DonaldAbility"),
    KH2Item(407, "Lucky Lucky", "DonaldAbility"),
    KH2Item(408, "Fire Boost", "DonaldAbility"),
    KH2Item(409, "Blizzard Boost", "DonaldAbility"),
    KH2Item(410, "Thunder Boost", "DonaldAbility"),
    KH2Item(408, "Fire Boost", "DonaldAbility"),
    KH2Item(409, "Blizzard Boost", "DonaldAbility"),
    KH2Item(410, "Thunder Boost", "DonaldAbility"),
    KH2Item(412, "MP Rage", "DonaldAbility"),
    KH2Item(421, "MP Hastera", "DonaldAbility"),
    KH2Item(417, "Auto Limit", "DonaldAbility"),
    KH2Item(419, "Hyper Healing", "DonaldAbility"),
    KH2Item(420, "Auto Healing", "DonaldAbility"),
    KH2Item(414, "Defender", "DonaldAbility"),
    KH2Item(411, "Item Boost", "DonaldAbility"),
    KH2Item(542, "Damage Control", "DonaldAbility"),
    KH2Item(419, "Hyper Healing", "DonaldAbility"),
    KH2Item(412, "MP Rage", "DonaldAbility"),
    KH2Item(413, "MP Haste", "DonaldAbility"),
    KH2Item(421, "MP Hastera", "DonaldAbility"),
    KH2Item(422, "MP Hastega", "DonaldAbility"),
]

goofyAbilityList = [
    KH2Item(423, "Goofy Tornado", "GoofyAbility"),
    KH2Item(425, "Goofy Turbo", "GoofyAbility"),
    KH2Item(429, "Goofy Bash", "GoofyAbility"),
    KH2Item(201, "Tornado Fusion", "GoofyAbility"),
    KH2Item(202, "Teamwork", "GoofyAbility"),
    KH2Item(405, "Draw", "GoofyAbility"),
    KH2Item(406, "Jackpot", "GoofyAbility"),
    KH2Item(407, "Lucky Lucky", "GoofyAbility"),
    KH2Item(411, "Item Boost", "GoofyAbility"),
    KH2Item(412, "MP Rage", "GoofyAbility"),
    KH2Item(414, "Defender", "GoofyAbility"),
    KH2Item(542, "Damage Control", "GoofyAbility"),
    KH2Item(417, "Auto Limit", "GoofyAbility"),
    KH2Item(415,"Second Chance","GoofyAbility"),
    KH2Item(416,"Once More","GoofyAbility"),
    KH2Item(418, "Auto Change", "GoofyAbility"),
    KH2Item(419, "Hyper Healing", "GoofyAbility"),
    KH2Item(420, "Auto Healing", "GoofyAbility"),
    KH2Item(414, "Defender", "GoofyAbility"),
    KH2Item(419, "Hyper Healing", "GoofyAbility"),
    KH2Item(413, "MP Haste", "GoofyAbility"),
    KH2Item(421, "MP Hastera", "GoofyAbility"),
    KH2Item(412, "MP Rage", "GoofyAbility"),
    KH2Item(422, "MP Hastega", "GoofyAbility"),
    KH2Item(411, "Item Boost", "GoofyAbility"),
    KH2Item(542, "Damage Control", "GoofyAbility"),
    KH2Item(596, "Protect", "GoofyAbility"),
    KH2Item(597, "Protera", "GoofyAbility"),
    KH2Item(598, "Protega", "GoofyAbility"),
]
