Program 0x00
Spawn "b_80"

Program 0x01
Party DEFAULT
AreaSettings 7 -1
	SetProgressFlag 0x10A5
	SetJump Type 1 World HB Area 24 Entrance 21 LocalSet 0 FadeType 1
	SetPartyMenu 0


Program 0x02
Party DEFAULT
AreaSettings 1 -1
	SetProgressFlag 0x10C0
	SetPartyMenu 0

AreaSettings 7 -1
	SetProgressFlag 0x10A7
	SetJump Type 1 World HB Area 24 Entrance 22 LocalSet 0 FadeType 1
	SetPartyMenu 0

Spawn "b_80"

Program 0x03
AreaSettings 1 -1
	SetProgressFlag 0x10C1
	SetPartyMenu 0

Spawn "b_80"