Program 0x61
AreaSettings 0 -1
	SetEvent "111s" Type 66
	SetJump Type 2 World CA Area 0 Entrance 0 LocalSet 98 FadeType 1
	SetPartyMenu 0


Program 0x60
Bgm Default Default
AreaSettings 0 -1
	SetEvent "109" Type 66
	SetJump Type 2 World CA Area 0 Entrance 0 LocalSet 97 FadeType 1
	SetPartyMenu 0


Program 0x4F
Party W_FRIEND
Bgm Default Default
AreaSettings 0 -1
	SetProgressFlag 0x400B
	SetEvent "109" Type 2
	SetJump Type 1 World CA Area 3 Entrance 51 LocalSet 0 FadeType 1
	SetPartyMenu 0
