Program 0x0A
Capacity 6.3E-44
Spawn "b_20"

Program 0x39
Capacity 6.6E-44
Party DEFAULT
Mission 0x40 "AL00_MS101"
Unk1d 3
Spawn "b_40"

Program 0x01
Capacity 6.2E-44
Spawn "b_00"

Program 0x02
Capacity 6.2E-44
Spawn "b_01"

Program 0x19
Spawn "z_70"

Program 0x6D
Mission 0x12D "AL00_SKATE_01"
Unk1d 1
Spawn "s_99"
Spawn "s_90"

Program 0x6E
Mission 0x12D "AL00_SKATE_01"
Unk1d 1
Spawn "s_99"
Spawn "s_90"