Program 0x15
Spawn "b01_"

Program 0x0A
Party W_FRIEND_FIX
AreaSettings 9 -1
	SetProgressFlag 0x281D
	SetEvent "205" Type 1
	SetJump Type 1 World LK Area 1 Entrance 50 LocalSet 0 FadeType 1
	SetPartyMenu 0

Spawn "b51e"

Program 0x16
Spawn "b00_"

Program 0x00


Program 0x10
Spawn "b55_"

Program 0x11
Spawn "b53_"

Program 0x12
Spawn "b54_"

Program 0x13
Spawn "e_50"
Spawn "b52_"

Program 0x14
Spawn "b50_"