Program 0x01
Party W_FRIEND
Bgm 98 98
AreaSettings 0 -1
	SetProgressFlag 0x1C09
	SetEvent "109" Type 2
	SetJump Type 1 World AL Area 7 Entrance 50 LocalSet 0 FadeType 1
	SetPartyMenu 0

Spawn "e_50"

Program 0x02
Party W_FRIEND
AreaSettings 1 -1
	SetProgressFlag 0x1C29
	SetPartyMenu 0

Spawn "e_50"

Program 0x77
Bgm 98 98
AreaSettings 0 -1
	SetEvent "109" Type 66
	SetJump Type 2 World AL Area 0 Entrance 0 LocalSet 120 FadeType 1
	SetPartyMenu 0
