Program 0x16
MapScript 15
Spawn "e_50"

Program 0x00
Spawn "e_50"

Program 0x01
Party NO_FRIEND
AreaSettings 0 -1
	SetProgressFlag 0x887
	SetEvent "609" Type 2
	SetJump Type 1 World TT Area 17 Entrance 50 LocalSet 0 FadeType 1
	SetPartyMenu 0


Program 0x13D
Bgm Default Default
AreaSettings 0 -1
	SetEvent "609" Type 66
	SetJump Type 2 World TT Area 0 Entrance 0 LocalSet 318 FadeType 1
	SetPartyMenu 0
