from Class.locationClass import *
from Class.itemClass import *
from List.configDict import itemType, locationType

class Locations:
    def getTreasureList(trueRandom=False):
        return [
            KH2Treasure(245, "Bamboo Grove Dark Shard", LocationTypes=[locationType.LoD]).setLocationWeight(-10),
            KH2Treasure(497, "Bamboo Grove Ether", LocationTypes=[locationType.LoD]).setLocationWeight(-10),
            KH2Treasure(498, "Bamboo Grove Mythril Shard", LocationTypes=[locationType.LoD]).setLocationWeight(-10),
            KH2Treasure(350, "Bamboo Grove Encampment Area Map", LocationTypes=[locationType.LoD], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(417, "Missions", LocationTypes=[locationType.LoD], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(21, "Checkpoint Hi-Potion", LocationTypes=[locationType.LoD]),
            KH2Treasure(121, "Checkpoint Mythril Shard", LocationTypes=[locationType.LoD]),
            KH2Treasure(22, "Mountain Trail Lightning Shard", LocationTypes=[locationType.LoD]),
            KH2Treasure(23, "Mountain Trail Recovery Recipe", LocationTypes=[locationType.LoD]),
            KH2Treasure(122, "Mountain Trail Ether", LocationTypes=[locationType.LoD]),
            KH2Treasure(123, "Mountain Trail Mythril Shard", LocationTypes=[locationType.LoD]),
            KH2Treasure(124, "Village Cave AP Boost", LocationTypes=[locationType.LoD]),
            KH2Treasure(125, "Village Cave Dark Shard", LocationTypes=[locationType.LoD]),
            KH2Treasure(495, "Village Cave Area Map", LocationTypes=[locationType.LoD], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(24, "Ridge Frost Shard", LocationTypes=[locationType.LoD]),
            KH2Treasure(126, "Ridge AP Boost", LocationTypes=[locationType.LoD]),
            KH2Treasure(257, "Hidden Dragon", LocationTypes=[locationType.LoD], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(25, "Throne Room Torn Pages", LocationTypes=[locationType.LoD]).setLocationWeight(10),
            KH2Treasure(127, "Throne Room Palace Map", LocationTypes=[locationType.LoD]).setLocationWeight(10),
            KH2Treasure(26, "Throne Room AP Boost", LocationTypes=[locationType.LoD]).setLocationWeight(10),
            KH2Treasure(27, "Throne Room Queen Recipe", LocationTypes=[locationType.LoD]).setLocationWeight(10),
            KH2Treasure(128, "Throne Room AP Boost", LocationTypes=[locationType.LoD]).setLocationWeight(10),
            KH2Treasure(129, "Throne Room Ogre Shield", LocationTypes=[locationType.LoD]).setLocationWeight(10),
            KH2Treasure(130, "Throne Room Mythril Crystal", LocationTypes=[locationType.LoD]).setLocationWeight(10),
            KH2Treasure(131, "Throne Room Orichalcum", LocationTypes=[locationType.LoD]).setLocationWeight(10),
            KH2Treasure(555, "Xigbar (Data) Defense Boost", LocationTypes=[locationType.LoD, locationType.DataOrg], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),


            KH2Treasure(353, "Agrabah Map", LocationTypes=[locationType.Agrabah], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(-10),
            KH2Treasure(28, "Agrabah Dark Shard", LocationTypes=[locationType.Agrabah]).setLocationWeight(-10),
            KH2Treasure(29, "Agrabah Mythril Shard", LocationTypes=[locationType.Agrabah]).setLocationWeight(-10),
            KH2Treasure(30, "Agrabah Hi-Potion", LocationTypes=[locationType.Agrabah]).setLocationWeight(-10),
            KH2Treasure(132, "Agrabah AP Boost", LocationTypes=[locationType.Agrabah]).setLocationWeight(-10),
            KH2Treasure(133, "Agrabah Mythril Stone", LocationTypes=[locationType.Agrabah]).setLocationWeight(-10),
            KH2Treasure(249, "Agrabah Mythril Shard", LocationTypes=[locationType.Agrabah]).setLocationWeight(-10),
            KH2Treasure(501, "Agrabah Serenity Shard", LocationTypes=[locationType.Agrabah]).setLocationWeight(-10),
            KH2Treasure(31, "Bazaar Mythril Gem", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(32, "Bazaar Power Shard", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(33, "Bazaar Hi-Potion", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(134, "Bazaar AP Boost", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(135, "Bazaar Mythril Shard", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(136, "Palace Walls Skill Ring", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(520, "Palace Walls Mythril Stone", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(250, "Cave Entrance Power Stone", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(251, "Cave Entrance Mythril Shard", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(35, "Valley of Stone Mythril Stone", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(36, "Valley of Stone AP Boost", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(137, "Valley of Stone Mythril Shard", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(138, "Valley of Stone Hi-Potion", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(487, "Chasm of Challenges Cave of Wonders Map", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(37, "Chasm of Challenges AP Boost", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(502, "Treasure Room AP Boost", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(503, "Treasure Room Serenity Gem", LocationTypes=[locationType.Agrabah]),
            KH2Treasure(300, "Lamp Charm", LocationTypes=[locationType.Agrabah], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(34, "Ruined Chamber Torn Pages", LocationTypes=[locationType.Agrabah], InvalidChecks=[] if trueRandom else [itemType.FIRE, itemType.BLIZZARD, itemType.THUNDER]).setLocationWeight(10),
            KH2Treasure(486, "Ruined Chamber Ruins Map", LocationTypes=[locationType.Agrabah], InvalidChecks=[] if trueRandom else [itemType.FIRE, itemType.BLIZZARD, itemType.THUNDER]).setLocationWeight(10),
            KH2Treasure(303, "Wishing Lamp", LocationTypes=[locationType.Agrabah], InvalidChecks=([] if trueRandom else [itemType.FIRE, itemType.BLIZZARD, itemType.THUNDER]) + [itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(545, "Lexaeus (AS) Strength Beyond Strength", LocationTypes=[locationType.Agrabah, locationType.AS], InvalidChecks=([] if trueRandom else [itemType.FIRE, itemType.BLIZZARD, itemType.THUNDER])+[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(550, "Lexaeus (Data) Lost Illusion", LocationTypes=[locationType.Agrabah, locationType.AS], InvalidChecks=([] if trueRandom else [itemType.FIRE, itemType.BLIZZARD, itemType.THUNDER])+[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(16, "Courtyard Mythril Shard", LocationTypes=[locationType.DC]).setLocationWeight(-10),
            KH2Treasure(17, "Courtyard Star Recipe", LocationTypes=[locationType.DC]).setLocationWeight(-10),
            KH2Treasure(18, "Courtyard AP Boost", LocationTypes=[locationType.DC]).setLocationWeight(-10),
            KH2Treasure(92, "Courtyard Mythril Stone", LocationTypes=[locationType.DC]).setLocationWeight(-10),
            KH2Treasure(93, "Courtyard Blazing Stone", LocationTypes=[locationType.DC]).setLocationWeight(-10),
            KH2Treasure(247, "Courtyard Blazing Shard", LocationTypes=[locationType.DC]).setLocationWeight(-10),
            KH2Treasure(248, "Courtyard Mythril Shard", LocationTypes=[locationType.DC]).setLocationWeight(-10),
            KH2Treasure(91, "Library Torn Pages", LocationTypes=[locationType.DC]),
            KH2Treasure(332, "Disney Castle Map", LocationTypes=[locationType.DC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(79, "Cornerstone Hill Map", LocationTypes=[locationType.DC]),
            KH2Treasure(12, "Cornerstone Hill Frost Shard", LocationTypes=[locationType.DC]),
            KH2Treasure(81, "Pier Mythril Shard", LocationTypes=[locationType.DC]),
            KH2Treasure(82, "Pier Hi-Potion", LocationTypes=[locationType.DC]),
            KH2Treasure(83, "Waterway Mythril Stone", LocationTypes=[locationType.DC]),
            KH2Treasure(84, "Waterway AP Boost", LocationTypes=[locationType.DC]),
            KH2Treasure(85, "Waterway Frost Stone", LocationTypes=[locationType.DC]),
            KH2Treasure(368, "Window of Time Map", LocationTypes=[locationType.DC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(261, "Monochrome", LocationTypes=[locationType.DC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(262, "Wisdom Form", LocationTypes=[locationType.DC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(548, "Marluxia (AS) Eternal Blossom", LocationTypes=[locationType.DC, locationType.AS], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(553, "Marluxia (Data) Lost Illusion", LocationTypes=[locationType.DC, locationType.AS], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(587, "Lingering Will Proof of Connection", LocationTypes=[locationType.DC, locationType.LW], InvalidChecks=([] if trueRandom else [itemType.FORM, itemType.THUNDER, itemType.MAGNET, itemType.TORN_PAGE])+[itemType.PROOF_OF_CONNECTION, itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(591, "Lingering Will Manifest Illusion", LocationTypes=[locationType.DC, locationType.LW], InvalidChecks=([] if trueRandom else [itemType.FORM, itemType.THUNDER, itemType.MAGNET, itemType.TORN_PAGE])+[itemType.PROOF_OF_CONNECTION, itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(313, "Pooh's House 100 Acre Wood Map", LocationTypes=[locationType.HUNDREDAW]).setLocationWeight(-10),
            KH2Treasure(97, "Pooh's House AP Boost", LocationTypes=[locationType.HUNDREDAW]).setLocationWeight(-10),
            KH2Treasure(98, "Pooh's House Mythril Stone", LocationTypes=[locationType.HUNDREDAW]).setLocationWeight(-10),
            KH2Treasure(105, "Piglet's House Defense Boost", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]),
            KH2Treasure(103, "Piglet's House AP Boost", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]),
            KH2Treasure(104, "Piglet's House Mythril Gem", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]),
            KH2Treasure(314, "Rabbit's House Draw Ring", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]),
            KH2Treasure(100, "Rabbit's House Mythril Crystal", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]),
            KH2Treasure(101, "Rabbit's House AP Boost", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]),
            KH2Treasure(108, "Kanga's House Magic Boost", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]),
            KH2Treasure(106, "Kanga's House AP Boost", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]),
            KH2Treasure(107, "Kanga's House Orichalcum", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]),
            KH2Treasure(110, "Spooky Cave Mythril Gem", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]).setLocationWeight(10),
            KH2Treasure(111, "Spooky Cave AP Boost", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]).setLocationWeight(10),
            KH2Treasure(112, "Spooky Cave Orichalcum", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]).setLocationWeight(10),
            KH2Treasure(113, "Spooky Cave Guard Recipe", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]).setLocationWeight(10),
            KH2Treasure(115, "Spooky Cave Mythril Crystal", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]).setLocationWeight(10),
            KH2Treasure(116, "Spooky Cave AP Boost", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]).setLocationWeight(10),
            KH2Treasure(284, "Sweet Memories", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=([] if trueRandom else [itemType.TORN_PAGE]) + [itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(485, "Spooky Cave Map", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=([] if trueRandom else [itemType.TORN_PAGE]) + [itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(312, "Starry Hill Cosmic Ring", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]).setLocationWeight(10),
            KH2Treasure(94, "Starry Hill Style Recipe", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=[] if trueRandom else [itemType.TORN_PAGE]).setLocationWeight(10),
            KH2Treasure(285, "Starry Hill Cure Element", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=([] if trueRandom else [itemType.TORN_PAGE]) + [itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(539, "Starry Hill Orichalcum+", LocationTypes=[locationType.HUNDREDAW], InvalidChecks=([] if trueRandom else [itemType.TORN_PAGE]) + [itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(7,"Passage Mythril Shard", LocationTypes=[locationType.OC]).setLocationWeight(-10),
            KH2Treasure(8,"Passage Mythril Stone", LocationTypes=[locationType.OC]).setLocationWeight(-10),
            KH2Treasure(144, "Passage Ether", LocationTypes=[locationType.OC]).setLocationWeight(-10),
            KH2Treasure(145, "Passage AP Boost", LocationTypes=[locationType.OC]).setLocationWeight(-10),
            KH2Treasure(146, "Passage Hi-Potion", LocationTypes=[locationType.OC]).setLocationWeight(-10),
            KH2Treasure(2,"Inner Chamber Underworld Map", LocationTypes=[locationType.OC]).setLocationWeight(-10),
            KH2Treasure(243, "Inner Chamber Mythril Shard", LocationTypes=[locationType.OC]).setLocationWeight(-10),
            KH2Treasure(338, "Coliseum Map", LocationTypes=[locationType.OC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(242, "Underworld Entrance Power Boost", LocationTypes=[locationType.OC]),
            KH2Treasure(3,"Caverns Entrance Lucid Shard", LocationTypes=[locationType.OC]),
            KH2Treasure(11, "Caverns Entrance AP Boost", LocationTypes=[locationType.OC]),
            KH2Treasure(504, "Caverns Entrance Mythril Shard", LocationTypes=[locationType.OC]),
            KH2Treasure(9,"The Lost Road Bright Shard", LocationTypes=[locationType.OC]),
            KH2Treasure(10, "The Lost Road Ether", LocationTypes=[locationType.OC]),
            KH2Treasure(148, "The Lost Road Mythril Shard", LocationTypes=[locationType.OC]),
            KH2Treasure(149, "The Lost Road Mythril Stone", LocationTypes=[locationType.OC]),
            KH2Treasure(150, "Atrium Lucid Stone", LocationTypes=[locationType.OC]),
            KH2Treasure(151, "Atrium AP Boost", LocationTypes=[locationType.OC]),
            KH2Treasure(529, "Secret Ansem Report 5", LocationTypes=[locationType.OC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(293, "Olympus Stone", LocationTypes=[locationType.OC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(244, "The Lock Caverns Map", LocationTypes=[locationType.OC]),
            KH2Treasure(5,"The Lock Mythril Shard", LocationTypes=[locationType.OC]),
            KH2Treasure(142, "The Lock AP Boost", LocationTypes=[locationType.OC]),
            KH2Treasure(260, "Hero´s Crest", LocationTypes=[locationType.OC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(295, "Auron´s Statue", LocationTypes=[locationType.OC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(272, "Guardian Soul", LocationTypes=[locationType.OC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(513, "Protect Belt (Pain and Panic Cup)", LocationTypes=[locationType.OC, locationType.OCCups], InvalidChecks=[itemType.TROPHY, itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(540, "Serenity Gem (Pain and Panic Cup)", LocationTypes=[locationType.OC, locationType.OCCups], InvalidChecks=[itemType.TROPHY,itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(515, "Rising Dragon (Cerberus Cup)", LocationTypes=[locationType.OC, locationType.OCCups], InvalidChecks=[itemType.TROPHY,itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(542, "Serenity Crystal (Cerberus Cup)", LocationTypes=[locationType.OC, locationType.OCCups], InvalidChecks=[itemType.TROPHY,itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(514, "Genji Shield (Titan Cup)", LocationTypes=[locationType.OC, locationType.OCCups], InvalidChecks=[itemType.TROPHY,itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(541, "Skillful Ring (Titan Cup)", LocationTypes=[locationType.OC, locationType.OCCups], InvalidChecks=[itemType.TROPHY,itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(516, "Fatal Crest (Goddess of Fate Cup)", LocationTypes=[locationType.OC, locationType.OCCups], InvalidChecks=[itemType.TROPHY,itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(517, "Orichalcum+ (Goddess of Fate Cup)", LocationTypes=[locationType.OC, locationType.OCCups], InvalidChecks=[itemType.TROPHY,itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(518, "Hades Cup Trophy (Paradox Cups)", LocationTypes=[locationType.OC, locationType.OCCups, locationType.OCParadoxCup], InvalidChecks=([] if trueRandom else [itemType.TORN_PAGE, itemType.FIRE, itemType.BLIZZARD, itemType.THUNDER, itemType.CURE, itemType.MAGNET, itemType.REFLECT])+[itemType.TROPHY, itemType.FORM, itemType.SUMMON, itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(546, "Zexion (AS) Book of Shadows", LocationTypes=[locationType.OC, locationType.AS], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(551, "Zexion (Data) Lost Illusion", LocationTypes=[locationType.OC, locationType.AS], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(39, "Courtyard AP Boost", LocationTypes=[locationType.BC]).setLocationWeight(-10),
            KH2Treasure(40, "Courtyard Hi-Potion", LocationTypes=[locationType.BC]).setLocationWeight(-10),
            KH2Treasure(505, "Courtyard Mythril Shard", LocationTypes=[locationType.BC]).setLocationWeight(-10),
            KH2Treasure(46, "Belle's Room Castle Map", LocationTypes=[locationType.BC]).setLocationWeight(-10),
            KH2Treasure(240, "Belle's Room Mega-Recipe", LocationTypes=[locationType.BC]).setLocationWeight(-10),
            KH2Treasure(63, "The East Wing Mythril Shard", LocationTypes=[locationType.BC]).setLocationWeight(-10),
            KH2Treasure(155, "The East Wing Tent", LocationTypes=[locationType.BC]).setLocationWeight(-10),
            KH2Treasure(41, "The West Hall Hi-Potion", LocationTypes=[locationType.BC]),
            KH2Treasure(207, "The West Hall Power Shard", LocationTypes=[locationType.BC]),
            KH2Treasure(208, "The West Hall Mythril Shard (Post Dungeon)", LocationTypes=[locationType.BC]),
            KH2Treasure(158, "The West Hall AP Boost", LocationTypes=[locationType.BC]),
            KH2Treasure(159, "The West Hall Bright Stone", LocationTypes=[locationType.BC]),
            KH2Treasure(239, "Dungeon Basement Map", LocationTypes=[locationType.BC]),
            KH2Treasure(43, "Dungeon AP Boost", LocationTypes=[locationType.BC]),
            KH2Treasure(44, "Secret Passage Mythril Shard", LocationTypes=[locationType.BC]),
            KH2Treasure(168, "Secret Passage Hi-Potion", LocationTypes=[locationType.BC]),
            KH2Treasure(45, "Secret Passage Lucid Shard", LocationTypes=[locationType.BC]),
            KH2Treasure(206, "The West Hall Mythril Shard", LocationTypes=[locationType.BC]),
            KH2Treasure(42, "The West Wing Mythril Shard", LocationTypes=[locationType.BC]),
            KH2Treasure(164, "The West Wing Tent", LocationTypes=[locationType.BC]),
            KH2Treasure(241, "The Beast's Room Blazing Shard", LocationTypes=[locationType.BC]),
            KH2Treasure(299, "Dark Thorn Cure Element", LocationTypes=[locationType.BC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(270, "Rumbling Rose", LocationTypes=[locationType.BC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(325, "Castle Walls Map", LocationTypes=[locationType.BC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(528, "Secret Ansem Report 6", LocationTypes=[locationType.BC], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(559, "Xaldin (Data) Defense Boost", LocationTypes=[locationType.BC, locationType.DataOrg], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),


            KH2Treasure(316, "Pit Cell Area Map", LocationTypes=[locationType.SP]).setLocationWeight(-10),
            KH2Treasure(64, "Pit Cell Mythril Crystal", LocationTypes=[locationType.SP]).setLocationWeight(-10),
            KH2Treasure(65, "Canyon Dark Crystal", LocationTypes=[locationType.SP]).setLocationWeight(-10),
            KH2Treasure(171, "Canyon Mythril Stone", LocationTypes=[locationType.SP]).setLocationWeight(-10),
            KH2Treasure(253, "Canyon Mythril Gem", LocationTypes=[locationType.SP]).setLocationWeight(-10),
            KH2Treasure(521, "Canyon Frost Crystal", LocationTypes=[locationType.SP]).setLocationWeight(-10),
            KH2Treasure(49, "Hallway Power Crystal", LocationTypes=[locationType.SP]),
            KH2Treasure(50, "Hallway AP Boost", LocationTypes=[locationType.SP]),
            KH2Treasure(255, "Communications Room I/O Tower Map", LocationTypes=[locationType.SP]),
            KH2Treasure(499, "Communications Room Gaia Belt", LocationTypes=[locationType.SP]),
            KH2Treasure(267, "Photon Debugger", LocationTypes=[locationType.SP], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(177, "Central Computer Core AP Boost", LocationTypes=[locationType.SP]).setLocationWeight(10),
            KH2Treasure(178, "Central Computer Core Orichalcum+", LocationTypes=[locationType.SP]).setLocationWeight(10),
            KH2Treasure(51, "Central Computer Core Cosmic Arts", LocationTypes=[locationType.SP]).setLocationWeight(10),
            KH2Treasure(488, "Central Computer Core Map", LocationTypes=[locationType.SP]).setLocationWeight(10),
            KH2Treasure(547, "Larxene (AS) Cloaked Thunder", LocationTypes=[locationType.SP, locationType.AS], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(552, "Larxene (Data) Lost Illusion", LocationTypes=[locationType.SP, locationType.AS], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(53, "Graveyard Mythril Shard", LocationTypes=[locationType.HT]).setLocationWeight(-10),
            KH2Treasure(212, "Graveyard Serenity Gem", LocationTypes=[locationType.HT]).setLocationWeight(-10),
            KH2Treasure(211, "Finklestein's Lab Halloween Town Map", LocationTypes=[locationType.HT]).setLocationWeight(-10),
            KH2Treasure(209, "Town Square Mythril Stone", LocationTypes=[locationType.HT]),
            KH2Treasure(210, "Town Square Energy Shard", LocationTypes=[locationType.HT]),
            KH2Treasure(54, "Hinterlands Lightning Shard", LocationTypes=[locationType.HT]),
            KH2Treasure(213, "Hinterlands Mythril Stone", LocationTypes=[locationType.HT]),
            KH2Treasure(214, "Hinterlands AP Boost", LocationTypes=[locationType.HT]),
            KH2Treasure(55, "Candy Cane Lane Mega-Potion", LocationTypes=[locationType.HT]),
            KH2Treasure(56, "Candy Cane Lane Mythril Gem", LocationTypes=[locationType.HT]),
            KH2Treasure(216, "Candy Cane Lane Lightning Stone", LocationTypes=[locationType.HT]),
            KH2Treasure(217, "Candy Cane Lane Mythril Stone", LocationTypes=[locationType.HT]),
            KH2Treasure(57, "Santa's House Christmas Town Map", LocationTypes=[locationType.HT]),
            KH2Treasure(58, "Santa's House AP Boost", LocationTypes=[locationType.HT]),
            KH2Treasure(301, "Oogie Boogie Magnet Element", LocationTypes=[locationType.HT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(297, "Present", LocationTypes=[locationType.HT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(298, "Decoy Presents", LocationTypes=[locationType.HT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(275, "Decisive Pumpkin", LocationTypes=[locationType.HT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(544, "Vexen (AS) Road to Discovery", LocationTypes=[locationType.HT, locationType.AS], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(549, "Vexen (Data) Lost Illusion", LocationTypes=[locationType.HT, locationType.AS], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(70, "Rampart Naval Map", LocationTypes=[locationType.PR]).setLocationWeight(-10),
            KH2Treasure(219, "Rampart Mythril Stone", LocationTypes=[locationType.PR]).setLocationWeight(-10),
            KH2Treasure(220, "Rampart Dark Shard", LocationTypes=[locationType.PR]).setLocationWeight(-10),
            KH2Treasure(71, "Town Dark Stone", LocationTypes=[locationType.PR]),
            KH2Treasure(72, "Town AP Boost", LocationTypes=[locationType.PR]),
            KH2Treasure(73, "Town Mythril Shard", LocationTypes=[locationType.PR]),
            KH2Treasure(221, "Town Mythril Gem", LocationTypes=[locationType.PR]),
            KH2Treasure(74, "Cave Mouth Bright Shard", LocationTypes=[locationType.PR]),
            KH2Treasure(223, "Cave Mouth Mythril Shard", LocationTypes=[locationType.PR]),
            KH2Treasure(329, "Isla de Muerta Map", LocationTypes=[locationType.PR], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(369, "Powder Store AP Boost (1)", LocationTypes=[locationType.PR]),
            KH2Treasure(370, "Powder Store AP Boost (2)", LocationTypes=[locationType.PR]),
            KH2Treasure(75, "Moonlight Nook Mythril Shard", LocationTypes=[locationType.PR]),
            KH2Treasure(224, "Moonlight Nook Serenity Gem", LocationTypes=[locationType.PR]),
            KH2Treasure(371, "Moonlight Nook Power Stone", LocationTypes=[locationType.PR]),
            KH2Treasure(263, "Follow the Wind", LocationTypes=[locationType.PR], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(252, "Interceptor's Hold Feather Charm", LocationTypes=[locationType.PR]),
            KH2Treasure(76, "Seadrift Keep AP Boost", LocationTypes=[locationType.PR]),
            KH2Treasure(225, "Seadrift Keep Orichalcum", LocationTypes=[locationType.PR]),
            KH2Treasure(372, "Seadrift Keep Meteor Staff", LocationTypes=[locationType.PR]),
            KH2Treasure(77, "Seadrift Row Serenity Gem", LocationTypes=[locationType.PR]),
            KH2Treasure(78, "Seadrift Row King Recipe", LocationTypes=[locationType.PR]),
            KH2Treasure(373, "Seadrift Row Mythril Crystal", LocationTypes=[locationType.PR]),
            KH2Treasure(296, "Seadrift Row Cursed Medallion", LocationTypes=[locationType.PR], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(331, "Seadrift Row Ship Graveyard Map", LocationTypes=[locationType.PR], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(530, "Secret Ansem Report 4", LocationTypes=[locationType.PR], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(557, "Luxord (Data) AP Boost", LocationTypes=[locationType.PR, locationType.DataOrg], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(362, "Marketplace Map", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(-10),
            KH2Treasure(194, "Borough Drive Recovery", LocationTypes=[locationType.HB]).setLocationWeight(-10),
            KH2Treasure(195, "Borough AP Boost", LocationTypes=[locationType.HB]).setLocationWeight(-10),
            KH2Treasure(196, "Borough Hi-Potion", LocationTypes=[locationType.HB]).setLocationWeight(-10),
            KH2Treasure(305, "Borough Mythril Shard", LocationTypes=[locationType.HB]).setLocationWeight(-10),
            KH2Treasure(506, "Borough Dark Shard", LocationTypes=[locationType.HB]).setLocationWeight(-10),
            KH2Treasure(256, "Merlin's House Membership Card", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(-10),
            KH2Treasure(292, "Merlin's House Blizzard Element", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(-10),
            KH2Treasure(531, "Bailey Secret Ansem Report 7", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(258, "Baseball Charm", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(310, "Postern Castle Perimeter Map", LocationTypes=[locationType.HB]),
            KH2Treasure(189, "Postern Mythril Gem", LocationTypes=[locationType.HB]),
            KH2Treasure(190, "Postern AP Boost", LocationTypes=[locationType.HB]),
            KH2Treasure(200, "Corridors Mythril Stone", LocationTypes=[locationType.HB]),
            KH2Treasure(201, "Corridors Mythril Crystal", LocationTypes=[locationType.HB]),
            KH2Treasure(202, "Corridors Dark Crystal", LocationTypes=[locationType.HB]),
            KH2Treasure(307, "Corridors AP Boost", LocationTypes=[locationType.HB]),
            KH2Treasure(184, "Ansem's Study Skill Recipe", LocationTypes=[locationType.HB]),
            KH2Treasure(266, "Ansem's Study Master Form", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(276, "Ansem's Study Sleeping Lion", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(183, "Ansem's Study Ukulele Charm", LocationTypes=[locationType.HB]),
            KH2Treasure(309, "Restoration Site Moon Recipe", LocationTypes=[locationType.HB]),
            KH2Treasure(507, "Restoration Site AP Boost", LocationTypes=[locationType.HB]),
            KH2Treasure(361, "FF Fights Cure Element", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(179, "Crystal Fissure Torn Pages", LocationTypes=[locationType.HB]),
            KH2Treasure(489, "Crystal Fissure The Great Maw Map", LocationTypes=[locationType.HB]),
            KH2Treasure(180, "Crystal Fissure Energy Crystal", LocationTypes=[locationType.HB]),
            KH2Treasure(181, "Crystal Fissure AP Boost", LocationTypes=[locationType.HB]),
            KH2Treasure(525, "1000 Heartless Secret Ansem Report 1", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(269, "1000 Heartless Ice Cream", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(511, "1000 Heartless Picture", LocationTypes=[locationType.HB], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(491, "Postern Gull Wing", LocationTypes=[locationType.HB]).setLocationWeight(10),
            KH2Treasure(311, "Heartless Manufactory Cosmic Chain", LocationTypes=[locationType.HB], InvalidChecks=[itemType.MEMBERSHIPCARD]),
            KH2Treasure(282, "Sephiroth Fenrir", LocationTypes=[locationType.HB, locationType.Sephi], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            #free
            KH2Treasure(562, "CoR Depths AP Boost", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(563, "CoR Depths Power Crystal", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(564, "CoR Depths Frost Crystal", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(565, "CoR Depths Manifest Illusion", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(566, "CoR Depths AP Boost", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(580, "CoR Mineshaft Lower Level Depths of Remembrance Map", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(578, "CoR Mineshaft Lower Level AP Boost", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            #post fight 1
            KH2Treasure(567, "CoR Depths Upper Level Remembrance Gem", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(568, "CoR Mining Area Serenity Gem", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(569, "CoR Mining Area AP Boost", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(570, "CoR Mining Area Serenity Crystal", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(571, "CoR Mining Area Manifest Illusion", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(572, "CoR Mining Area Serenity Gem", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(573, "CoR Mining Area Dark Remembrance Map", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            KH2Treasure(581, "CoR Mineshaft Mid Level Power Boost", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]),
            #post fight 2
            KH2Treasure(574, "CoR Engine Chamber Serenity Crystal", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]).setLocationWeight(10),
            KH2Treasure(575, "CoR Engine Chamber Remembrance Crystal", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]).setLocationWeight(10),
            KH2Treasure(576, "CoR Engine Chamber AP Boost", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]).setLocationWeight(10),
            KH2Treasure(577, "CoR Engine Chamber Manifest Illusion", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]).setLocationWeight(10),
            KH2Treasure(582, "CoR Mineshaft Upper Level Magic Boost", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]).setLocationWeight(10),
            #last chest
            KH2Treasure(579, "CoR Mineshaft Upper Level AP Boost", LocationTypes=[locationType.HB, locationType.CoR], InvalidChecks=[] if trueRandom else [itemType.FORM, itemType.GROWTH_ABILITY]).setLocationWeight(10),
            KH2Treasure(560, "Demyx (Data) AP Boost", LocationTypes=[locationType.HB, locationType.DataOrg], InvalidChecks=[itemType.FORM, itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(588, "Winner's Proof", LocationTypes=[locationType.HB], InvalidChecks=([] if trueRandom else [itemType.FORM, itemType.THUNDER, itemType.MAGNET, itemType.TORN_PAGE])+[itemType.PROOF_OF_PEACE, itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(589, "Proof of Peace", LocationTypes=[locationType.HB], InvalidChecks=([] if trueRandom else [itemType.FORM, itemType.THUNDER, itemType.MAGNET, itemType.TORN_PAGE])+[itemType.PROOF_OF_PEACE, itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
        
            KH2Treasure(492, "Gorge Savannah Map", LocationTypes=[locationType.PL]).setLocationWeight(-10),
            KH2Treasure(404, "Gorge Dark Gem", LocationTypes=[locationType.PL]).setLocationWeight(-10),
            KH2Treasure(405, "Gorge Mythril Stone", LocationTypes=[locationType.PL]).setLocationWeight(-10),
            KH2Treasure(401, "Elephant Graveyard Frost Gem", LocationTypes=[locationType.PL]),
            KH2Treasure(402, "Elephant Graveyard Mythril Stone", LocationTypes=[locationType.PL]),
            KH2Treasure(403, "Elephant Graveyard Bright Stone", LocationTypes=[locationType.PL]),
            KH2Treasure(508, "Elephant Graveyard AP Boost", LocationTypes=[locationType.PL]),
            KH2Treasure(509, "Elephant Graveyard Mythril Shard", LocationTypes=[locationType.PL]),
            KH2Treasure(418, "Pride Rock Map", LocationTypes=[locationType.PL]),
            KH2Treasure(392, "Pride Rock Mythril Stone", LocationTypes=[locationType.PL]),
            KH2Treasure(393, "Pride Rock Serenity Crystal", LocationTypes=[locationType.PL]),
            KH2Treasure(396, "Wildebeest Valley Energy Stone", LocationTypes=[locationType.PL]),
            KH2Treasure(397, "Wildebeest Valley AP Boost", LocationTypes=[locationType.PL]),
            KH2Treasure(398, "Wildebeest Valley Mythril Gem", LocationTypes=[locationType.PL]),
            KH2Treasure(399, "Wildebeest Valley Mythril Stone", LocationTypes=[locationType.PL]),
            KH2Treasure(400, "Wildebeest Valley Lucid Gem", LocationTypes=[locationType.PL]),
            KH2Treasure(406, "Wastelands Mythril Shard", LocationTypes=[locationType.PL]),
            KH2Treasure(407, "Wastelands Serenity Gem", LocationTypes=[locationType.PL]),
            KH2Treasure(408, "Wastelands Mythril Stone", LocationTypes=[locationType.PL]),
            KH2Treasure(409, "Jungle Serenity Gem", LocationTypes=[locationType.PL]),
            KH2Treasure(410, "Jungle Mythril Stone", LocationTypes=[locationType.PL]),
            KH2Treasure(411, "Jungle Serenity Crystal", LocationTypes=[locationType.PL]),
            KH2Treasure(412, "Oasis Map", LocationTypes=[locationType.PL]),
            KH2Treasure(493, "Oasis Torn Pages", LocationTypes=[locationType.PL]),
            KH2Treasure(413, "Oasis AP Boost", LocationTypes=[locationType.PL]),
            KH2Treasure(264, "Circle of Life", LocationTypes=[locationType.PL], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(302, "Scar Fire Element", LocationTypes=[locationType.PL], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(556, "Saix (Data) Defense Boost", LocationTypes=[locationType.PL, locationType.DataOrg], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(319, "Twilight Town Map", LocationTypes=[locationType.STT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(-10),
            KH2Treasure(288, "Munny Pouch (Olette)", LocationTypes=[locationType.STT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(-10),
            KH2Treasure(315, "Station of Serenity Potion", LocationTypes=[locationType.STT]).setLocationWeight(-10),
            KH2Treasure(472, "Station of Calling Potion", LocationTypes=[locationType.STT]).setLocationWeight(-10),
            KH2Treasure(389, "(Junk) Champion Belt", LocationTypes=[locationType.STT], InvalidChecks=[e for e in itemType]),
            KH2Treasure(390, "(Junk) Medal", LocationTypes=[locationType.STT], InvalidChecks=[e for e in itemType]),
            KH2Treasure(519, "The Struggle Trophy", LocationTypes=[locationType.STT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(428, "Central Station Potion (1)", LocationTypes=[locationType.STT]),
            KH2Treasure(429, "Central Station Hi-Potion", LocationTypes=[locationType.STT]),
            KH2Treasure(430, "Central Station Potion (2)", LocationTypes=[locationType.STT]),
            KH2Treasure(434, "Sunset Terrace Ability Ring", LocationTypes=[locationType.STT]),
            KH2Treasure(435, "Sunset Terrace Hi-Potion", LocationTypes=[locationType.STT]),
            KH2Treasure(436, "Sunset Terrace Potion (1)", LocationTypes=[locationType.STT]),
            KH2Treasure(437, "Sunset Terrace Potion (2)", LocationTypes=[locationType.STT]),
            KH2Treasure(449, "Mansion Foyer Hi-Potion", LocationTypes=[locationType.STT]),
            KH2Treasure(450, "Mansion Foyer Potion (1)", LocationTypes=[locationType.STT]),
            KH2Treasure(451, "Mansion Foyer Potion (2)", LocationTypes=[locationType.STT]),
            KH2Treasure(455, "Mansion Dining Room Elven Bandanna", LocationTypes=[locationType.STT]),
            KH2Treasure(456, "Mansion Dining Room Potion", LocationTypes=[locationType.STT]),
            KH2Treasure(289, "Naminé´s Sketches", LocationTypes=[locationType.STT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(483, "Mansion Map", LocationTypes=[locationType.STT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(459, "Mansion Library Hi-Potion", LocationTypes=[locationType.STT]),
            KH2Treasure(463, "Mansion Basement Corridor Hi-Potion", LocationTypes=[locationType.STT]),
            KH2Treasure(558, "Roxas (Data) Magic Boost", LocationTypes=[locationType.STT, locationType.DataOrg], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),



            KH2Treasure(447, "Old Mansion Potion", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(448, "Old Mansion Mythril Shard", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(442, "The Woods Potion", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(443, "The Woods Mythril Shard", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(444, "The Woods Hi-Potion", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(420, "Tram Common Hi-Potion", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(421, "Tram Common AP Boost", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(422, "Tram Common Tent", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(423, "Tram Common Mythril Shard (1)", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(424, "Tram Common Potion (1)", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(425, "Tram Common Mythril Shard (2)", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(484, "Tram Common Potion (2)", LocationTypes=[locationType.TT]).setLocationWeight(-10),
            KH2Treasure(526, "Station Plaza Secret Ansem Report 2", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(290, "Munny Pouch (Mickey)", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(291, "Crystal Orb", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(431, "Central Station Tent", LocationTypes=[locationType.TT]),
            KH2Treasure(432, "Central Station Hi-Potion", LocationTypes=[locationType.TT]),
            KH2Treasure(433, "Central Station Mythril Shard", LocationTypes=[locationType.TT]),
            KH2Treasure(465, "The Tower Potion", LocationTypes=[locationType.TT]),
            KH2Treasure(466, "The Tower Hi-Potion", LocationTypes=[locationType.TT]),
            KH2Treasure(522, "The Tower Ether", LocationTypes=[locationType.TT]),
            KH2Treasure(467, "Tower Entryway Ether", LocationTypes=[locationType.TT]),
            KH2Treasure(468, "Tower Entryway Mythril Shard", LocationTypes=[locationType.TT]),
            KH2Treasure(469, "Sorcerer's Loft Tower Map", LocationTypes=[locationType.TT]),
            KH2Treasure(470, "Tower Wardrobe Mythril Stone", LocationTypes=[locationType.TT]),
            KH2Treasure(304, "Star Seeker", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(286, "Valor Form", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(294, "Seifer´s Trophy", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(265, "Oathkeeper", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(543, "Limit Form", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(479, "Underground Concourse Mythril Gem", LocationTypes=[locationType.TT]),
            KH2Treasure(480, "Underground Concourse Orichalcum", LocationTypes=[locationType.TT]),
            KH2Treasure(481, "Underground Concourse AP Boost", LocationTypes=[locationType.TT]),
            KH2Treasure(482, "Underground Concourse Mythril Crystal", LocationTypes=[locationType.TT]),
            KH2Treasure(477, "Tunnelway Orichalcum", LocationTypes=[locationType.TT]),
            KH2Treasure(478, "Tunnelway Mythril Crystal", LocationTypes=[locationType.TT]),
            KH2Treasure(438, "Sunset Terrace Orichalcum+", LocationTypes=[locationType.TT]),
            KH2Treasure(439, "Sunset Terrace Mythril Shard", LocationTypes=[locationType.TT]),
            KH2Treasure(440, "Sunset Terrace Mythril Crystal", LocationTypes=[locationType.TT]),
            KH2Treasure(441, "Sunset Terrace AP Boost", LocationTypes=[locationType.TT]),
            KH2Treasure(452, "Mansion Foyer Mythril Crystal", LocationTypes=[locationType.TT]),
            KH2Treasure(453, "Mansion Foyer Mythril Stone", LocationTypes=[locationType.TT]),
            KH2Treasure(454, "Mansion Foyer Serenity Crystal", LocationTypes=[locationType.TT]),
            KH2Treasure(457, "Mansion Dining Room Mythril Crystal", LocationTypes=[locationType.TT]),
            KH2Treasure(458, "Mansion Dining Room Mythril Stone", LocationTypes=[locationType.TT]),
            KH2Treasure(460, "Mansion Library Orichalcum", LocationTypes=[locationType.TT]),
            KH2Treasure(534, "Beam Secret Ansem Report 10", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(464, "Mansion Basement Corridor Ultimate Recipe", LocationTypes=[locationType.TT]),
            KH2Treasure(317, "Betwixt and Between Bond of Flame", LocationTypes=[locationType.TT], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(561, "Axel (Data) Magic Boost", LocationTypes=[locationType.TT, locationType.DataOrg], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(374, "Fragment Crossing Mythril Stone", LocationTypes=[locationType.TWTNW]).setLocationWeight(-10),
            KH2Treasure(375, "Fragment Crossing Mythril Crystal", LocationTypes=[locationType.TWTNW]).setLocationWeight(-10),
            KH2Treasure(376, "Fragment Crossing AP Boost", LocationTypes=[locationType.TWTNW]).setLocationWeight(-10),
            KH2Treasure(377, "Fragment Crossing Orichalcum", LocationTypes=[locationType.TWTNW]).setLocationWeight(-10),
            KH2Treasure(532, "Roxas Secret Ansem Report 8", LocationTypes=[locationType.TWTNW], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(277, "Two Become One", LocationTypes=[locationType.TWTNW], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(391, "Memory's Skyscaper Mythril Crystal", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(523, "Memory's Skyscaper AP Boost", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(524, "Memory's Skyscaper Mythril Stone", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(335, "The Brink of Despair Dark City Map", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(500, "The Brink of Despair Orichalcum+", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(378, "Nothing's Call Mythril Gem", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(379, "Nothing's Call Orichalcum", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(336, "Twilight's View Cosmic Belt", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(527, "Xigbar Secret Ansem Report 3", LocationTypes=[locationType.TWTNW], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(380, "Naught's Skyway Mythril Gem", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(381, "Naught's Skyway Orichalcum", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(382, "Naught's Skyway Mythril Crystal", LocationTypes=[locationType.TWTNW]),
            KH2Treasure(278, "Oblivion", LocationTypes=[locationType.TWTNW], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(496, "Castle That Never Was Map", LocationTypes=[locationType.TWTNW], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(533, "Luxord Secret Ansem Report 9", LocationTypes=[locationType.TWTNW], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(536, "Saix Secret Ansem Report 12", LocationTypes=[locationType.TWTNW], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(535, "(Pre-Xemnas 1) Secret Ansem Report 11", LocationTypes=[locationType.TWTNW], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(385, "Ruin and Creation's Passage Mythril Stone", LocationTypes=[locationType.TWTNW]).setLocationWeight(10),
            KH2Treasure(386, "Ruin and Creation's Passage AP Boost", LocationTypes=[locationType.TWTNW]).setLocationWeight(10),
            KH2Treasure(387, "Ruin and Creation's Passage Mythril Crystal", LocationTypes=[locationType.TWTNW]).setLocationWeight(10),
            KH2Treasure(388, "Ruin and Creation's Passage Orichalcum", LocationTypes=[locationType.TWTNW]).setLocationWeight(10),
            KH2Treasure(537, "Xemnas 1 Secret Ansem Report 13", LocationTypes=[locationType.TWTNW], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(554, "Xemnas (Data) Power Boost", LocationTypes=[locationType.TWTNW, locationType.DataOrg], InvalidChecks=[itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),

            KH2Treasure(585, "Garden of Assemblage Map", LocationTypes=[locationType.Free]).setLocationWeight(-10),
            KH2Treasure(586, "GoA Lost Illusion", LocationTypes=[locationType.Free]).setLocationWeight(-10),
            KH2Treasure(590, "Proof of Nonexistence", LocationTypes=[locationType.Free]).setLocationWeight(-10),

            KH2Treasure(367, "Undersea Kingdom Map", LocationTypes=[locationType.Atlantica], InvalidChecks=([] if trueRandom else [itemType.MAGNET, itemType.THUNDER, itemType.TORN_PAGE, itemType.FORM])+ [itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]),
            KH2Treasure(287, "Mysterious Abyss", LocationTypes=[locationType.Atlantica], InvalidChecks=([] if trueRandom else [itemType.MAGNET, itemType.THUNDER, itemType.TORN_PAGE, itemType.FORM]) + [itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(279, "Musical Blizzard Element", LocationTypes=[locationType.Atlantica],  InvalidChecks=([] if trueRandom else [itemType.MAGNET, itemType.THUNDER, itemType.TORN_PAGE, itemType.FORM]) + [itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
            KH2Treasure(538, "Musical Orichalcum+", LocationTypes=[locationType.Atlantica],  InvalidChecks=([] if trueRandom else [itemType.MAGNET, itemType.THUNDER, itemType.TORN_PAGE, itemType.FORM]) + [itemType.GROWTH_ABILITY, itemType.SUPPORT_ABILITY, itemType.ACTION_ABILITY]).setLocationWeight(10),
]

    def getSoraLevelList():
        return [
            KH2LevelUp("Sora", 1),
            KH2LevelUp("Sora", 2),
            KH2LevelUp("Sora", 3),
            KH2LevelUp("Sora", 4),
            KH2LevelUp("Sora", 5),
            KH2LevelUp("Sora", 6),
            KH2LevelUp("Sora", 7),
            KH2LevelUp("Sora", 8),
            KH2LevelUp("Sora", 9),
            KH2LevelUp("Sora", 10),
            KH2LevelUp("Sora", 11),
            KH2LevelUp("Sora", 12),
            KH2LevelUp("Sora", 13),
            KH2LevelUp("Sora", 14),
            KH2LevelUp("Sora", 15),
            KH2LevelUp("Sora", 16),
            KH2LevelUp("Sora", 17),
            KH2LevelUp("Sora", 18),
            KH2LevelUp("Sora", 19),
            KH2LevelUp("Sora", 20),
            KH2LevelUp("Sora", 21),
            KH2LevelUp("Sora", 22),
            KH2LevelUp("Sora", 23),
            KH2LevelUp("Sora", 24),
            KH2LevelUp("Sora", 25),
            KH2LevelUp("Sora", 26),
            KH2LevelUp("Sora", 27),
            KH2LevelUp("Sora", 28),
            KH2LevelUp("Sora", 29),
            KH2LevelUp("Sora", 30),
            KH2LevelUp("Sora", 31),
            KH2LevelUp("Sora", 32),
            KH2LevelUp("Sora", 33),
            KH2LevelUp("Sora", 34),
            KH2LevelUp("Sora", 35),
            KH2LevelUp("Sora", 36),
            KH2LevelUp("Sora", 37),
            KH2LevelUp("Sora", 38),
            KH2LevelUp("Sora", 39),
            KH2LevelUp("Sora", 40),
            KH2LevelUp("Sora", 41),
            KH2LevelUp("Sora", 42),
            KH2LevelUp("Sora", 43),
            KH2LevelUp("Sora", 44),
            KH2LevelUp("Sora", 45),
            KH2LevelUp("Sora", 46),
            KH2LevelUp("Sora", 47),
            KH2LevelUp("Sora", 48),
            KH2LevelUp("Sora", 49),
            KH2LevelUp("Sora", 50),
            KH2LevelUp("Sora", 51),
            KH2LevelUp("Sora", 52),
            KH2LevelUp("Sora", 53),
            KH2LevelUp("Sora", 54),
            KH2LevelUp("Sora", 55),
            KH2LevelUp("Sora", 56),
            KH2LevelUp("Sora", 57),
            KH2LevelUp("Sora", 58),
            KH2LevelUp("Sora", 59),
            KH2LevelUp("Sora", 60),
            KH2LevelUp("Sora", 61),
            KH2LevelUp("Sora", 62),
            KH2LevelUp("Sora", 63),
            KH2LevelUp("Sora", 64),
            KH2LevelUp("Sora", 65),
            KH2LevelUp("Sora", 66),
            KH2LevelUp("Sora", 67),
            KH2LevelUp("Sora", 68),
            KH2LevelUp("Sora", 69),
            KH2LevelUp("Sora", 70),
            KH2LevelUp("Sora", 71),
            KH2LevelUp("Sora", 72),
            KH2LevelUp("Sora", 73),
            KH2LevelUp("Sora", 74),
            KH2LevelUp("Sora", 75),
            KH2LevelUp("Sora", 76),
            KH2LevelUp("Sora", 77),
            KH2LevelUp("Sora", 78),
            KH2LevelUp("Sora", 79),
            KH2LevelUp("Sora", 80),
            KH2LevelUp("Sora", 81),
            KH2LevelUp("Sora", 82),
            KH2LevelUp("Sora", 83),
            KH2LevelUp("Sora", 84),
            KH2LevelUp("Sora", 85),
            KH2LevelUp("Sora", 86),
            KH2LevelUp("Sora", 87),
            KH2LevelUp("Sora", 88),
            KH2LevelUp("Sora", 89),
            KH2LevelUp("Sora", 90),
            KH2LevelUp("Sora", 91),
            KH2LevelUp("Sora", 92),
            KH2LevelUp("Sora", 93),
            KH2LevelUp("Sora", 94),
            KH2LevelUp("Sora", 95),
            KH2LevelUp("Sora", 96),
            KH2LevelUp("Sora", 97),
            KH2LevelUp("Sora", 98),
            KH2LevelUp("Sora", 99)
        ]

    def getSoraBonusList(trueRandom=False):
        return [
            KH2Bonus(26,1,locationTypes=[locationType.TWTNW],description="Xemnas", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False, doubleReward=True), # moving here to make sure we don't get duplicate reward on this bonus
            KH2Bonus(2,1, locationTypes=[locationType.BC],description="Thresholder"),
            KH2Bonus(3,1, locationTypes=[locationType.BC],description="Dark Thorn", hasStat=True),
            KH2Bonus(4,1,locationTypes=[locationType.BC],description="Xaldin", hasStat=True).setLocationWeight(10),
            KH2Bonus(5,1,locationTypes=[locationType.OC],description="Cerberus"),
            KH2Bonus(6,1,locationTypes=[locationType.OC],description="Pete (OC)"),
            KH2Bonus(7,1,locationTypes=[locationType.OC],description="Hydra", hasStat=True),
            KH2Bonus(8,1, locationTypes=[locationType.OC],description="Hades", hasStat=True).setLocationWeight(10),
            KH2Bonus(9,1,locationTypes=[locationType.LoD],description="Shan-Yu", hasStat=True),
            KH2Bonus(12,1,locationTypes=[locationType.BC], description="Beast", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(10,1,locationTypes=[locationType.LoD],description="Storm Rider").setLocationWeight(10),
            KH2Bonus(47,1,locationTypes=[locationType.HB],description="Bailey"),
            KH2Bonus(16,1,locationTypes=[locationType.DC],description="Boat Pete"),
            KH2Bonus(17,1,locationTypes=[locationType.DC],description="Wharf Pete", hasStat=True),
            KH2Bonus(18,1,locationTypes=[locationType.HT],description="Prison Keeper", hasStat=True),
            KH2Bonus(19,1,locationTypes=[locationType.HT],description="Oogie Boogie", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(20,1,locationTypes=[locationType.HT],description="Experiment", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(21,1,locationTypes=[locationType.PR],description="Barbossa", hasStat=True),
            KH2Bonus(22,1,locationTypes=[locationType.PR],description="Grim Reaper 2").setLocationWeight(10),
            KH2Bonus(23,1,locationTypes=[locationType.TWTNW],description="Xigbar", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(24,1,locationTypes=[locationType.TWTNW],description="Luxord", hasStat=True),
            KH2Bonus(25,1,locationTypes=[locationType.TWTNW],description="Saix", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(28,1,locationTypes=[locationType.HB],description="Demyx (Hollow Bastion)", hasStat=True),
            KH2Bonus(29,1,locationTypes=[locationType.PL],description="Scar", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(30,1,locationTypes=[locationType.PL],description="Groundshaker", hasStat=True).setLocationWeight(10),
            KH2Bonus(31,1,locationTypes=[locationType.SP],description="Hostile Program", hasStat=True),
            KH2Bonus(32,1,locationTypes=[locationType.SP],description="MCP", hasStat=True).setLocationWeight(10),
            KH2Bonus(33,14,locationTypes=[locationType.STT],description="Twilight Thorn"),
            KH2Bonus(34,14,locationTypes=[locationType.STT],description="Axel 2", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(35,1,locationTypes=[locationType.HB, locationType.Sephi], description="Fenrir (Sephiroth)", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(37,1,locationTypes=[locationType.Agrabah],description="Elemental Lords"),
            KH2Bonus(38, 1, locationTypes=[locationType.DC],description="Minnie Escort", hasStat=True),
            KH2Bonus(39,1,locationTypes=[locationType.PR], description="Interceptor Barrels", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(40,1,locationTypes=[locationType.HT], description="Lock, Shock, and Barrel", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(42,1,locationTypes=[locationType.Agrabah],description="Abu Escort"),
            KH2Bonus(43,1,locationTypes=[locationType.LoD],description="Village Cave"),
            KH2Bonus(45,1,locationTypes=[locationType.SP],description="Screens", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(46,1,locationTypes=[locationType.Agrabah],description="Treasure Room", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(15,1,locationTypes=[locationType.Agrabah], description="Genie Jafar",  invalidChecks=([] if trueRandom else [itemType.FIRE, itemType.BLIZZARD, itemType.THUNDER])).setLocationWeight(10),
            KH2Bonus(49,1,locationTypes=[locationType.PL], description="Hyenas 1",  invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(50,1,locationTypes=[locationType.PL],  description="Hyenas 2", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(54,14,locationTypes=[locationType.STT],description="Station Dusks"),
            KH2Bonus(56,1,locationTypes=[locationType.TT],  description="Mansion Nobodies", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(57,1,locationTypes=[locationType.OC],description="Urns"),
            KH2Bonus(58,1,locationTypes=[locationType.OC],  description="Demyx OC", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(59,1,locationTypes=[locationType.PR],description="Grim Reaper"),
            KH2Bonus(60,1,locationTypes=[locationType.HB],description="1000 Heartless").setLocationWeight(10),
            KH2Bonus(61,1,locationTypes=[locationType.SP],description="Solar Sailer").setLocationWeight(10),
            KH2Bonus(62,1,locationTypes=[locationType.PR],description="Boat Fight"),
            KH2Bonus(63,1,locationTypes=[locationType.TT],description="Betwixt and Between").setLocationWeight(10),
            KH2Bonus(64,1,locationTypes=[locationType.HT, locationType.AS], description="Vexen (AS)",  invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(65,1,locationTypes=[locationType.Agrabah, locationType.AS],  description="Lexaeus (AS)", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(66,1,locationTypes=[locationType.OC, locationType.AS], description="Zexion (AS)",  invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(67,1,locationTypes=[locationType.DC, locationType.AS], description="Marluxia (AS)", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(68,1,locationTypes=[locationType.SP, locationType.AS], description="Larxene (AS)", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(69,1,locationTypes=[locationType.TWTNW],description="Roxas", hasStat=True),
            KH2Bonus(70,1,locationTypes=[locationType.DC, locationType.LW],description="Lingering Will", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(71,1,locationTypes=[locationType.TWTNW], description="Final Xemnas", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(72,1,locationTypes=[locationType.HB],description="Transport to Remembrance", invalidChecks=[e for e in itemType], hasStat=True, hasItem=False),
            KH2Bonus(73,14,locationTypes=[locationType.STT],description="Axel 1")
        ]

    def getSoraStartingItemList():
        soraStartingItem = KH2StartingItem(1,7, LocationTypes=[locationType.Critical], ArmorSlotMax=1, AccessorySlotMax=1, ItemSlotMax=3)
        return [soraStartingItem, soraStartingItem, soraStartingItem, soraStartingItem, soraStartingItem, soraStartingItem, soraStartingItem]

    def getFormLevelList(trueRandom=False):
        formLevels = [
            KH2FormLevel(1,1),
            KH2FormLevel(1,2).setLocationWeight(-10),
            KH2FormLevel(1,3).setLocationWeight(-10),
            KH2FormLevel(1,4),
            KH2FormLevel(1,5).setLocationWeight(10),
            KH2FormLevel(1,6).setLocationWeight(10),
            KH2FormLevel(1,7).setLocationWeight(10),
            KH2FormLevel(2,1),
            KH2FormLevel(2,2).setLocationWeight(-10),
            KH2FormLevel(2,3).setLocationWeight(-10),
            KH2FormLevel(2,4),
            KH2FormLevel(2,5).setLocationWeight(10),
            KH2FormLevel(2,6).setLocationWeight(10),
            KH2FormLevel(2,7).setLocationWeight(10),
            KH2FormLevel(3,1),
            KH2FormLevel(3,2).setLocationWeight(-10),
            KH2FormLevel(3,3).setLocationWeight(-10),
            KH2FormLevel(3,4),
            KH2FormLevel(3,5).setLocationWeight(10),
            KH2FormLevel(3,6).setLocationWeight(10),
            KH2FormLevel(3,7).setLocationWeight(10),
            KH2FormLevel(4,1),
            KH2FormLevel(4,2).setLocationWeight(-10),
            KH2FormLevel(4,3).setLocationWeight(-10),
            KH2FormLevel(4,4),
            KH2FormLevel(4,5).setLocationWeight(10),
            KH2FormLevel(4,6).setLocationWeight(10),
            KH2FormLevel(4,7).setLocationWeight(10),
            KH2FormLevel(5,1),
            KH2FormLevel(5,2).setLocationWeight(-10),
            KH2FormLevel(5,3).setLocationWeight(-10),
            KH2FormLevel(5,4),
            KH2FormLevel(5,5).setLocationWeight(10),
            KH2FormLevel(5,6).setLocationWeight(10),
            KH2FormLevel(5,7).setLocationWeight(10),
            KH2FormLevel(0,1, LocationTypes=["SummonLevel"]),
            KH2FormLevel(0,2, LocationTypes=["SummonLevel"]),
            KH2FormLevel(0,3, LocationTypes=["SummonLevel"]),
            KH2FormLevel(0,4, LocationTypes=["SummonLevel"]),
            KH2FormLevel(0,5, LocationTypes=["SummonLevel"]),
            KH2FormLevel(0,6, LocationTypes=["SummonLevel"]),
            KH2FormLevel(0,7, LocationTypes=["SummonLevel"]),

        ]
        if trueRandom:
            for lv in formLevels:
                  lv.InvalidChecks = []
        return formLevels

    def getSoraWeaponList():
        return [
            KH2ItemStat(116,Name="FAKE"),
            KH2ItemStat(83,Name="Detection Saber"),
            KH2ItemStat(84,Name="Edge of Ultima"),
            KH2ItemStat(80,Name="Kingdom Key"),
            KH2ItemStat(81,Name="Oathkeeper"),
            KH2ItemStat(82,Name="Oblivion"),
            KH2ItemStat(123,Name="Star Seeker"),
            KH2ItemStat(124,Name="Hidden Dragon"),
            KH2ItemStat(127,Name="Hero's Crest"),
            KH2ItemStat(128,Name="Monochrome"),
            KH2ItemStat(129,Name="Follow the Wind"),
            KH2ItemStat(130,Name="Circle of Life"),
            KH2ItemStat(131,Name="Photon Debugger"),
            KH2ItemStat(132,Name="Gull Wing"),
            KH2ItemStat(133,Name="Rumbling Rose"),
            KH2ItemStat(134,Name="Guardian Soul"),
            KH2ItemStat(135,Name="Wishing Lamp"),
            KH2ItemStat(136,Name="Decisive Pumpkin"),
            KH2ItemStat(138,Name="Sweet Memories"),
            KH2ItemStat(139,Name="Mysterious Abyss"),
            KH2ItemStat(137,Name="Sleeping Lion"),
            KH2ItemStat(141,Name="Bond of Flame"),
            KH2ItemStat(148,Name="Two Become One"),
            KH2ItemStat(140,Name="Fatal Crest"),
            KH2ItemStat(142,Name="Fenrir"),
            KH2ItemStat(143,Name="Ultima Weapon"),
            KH2ItemStat(149,Name="Winner's Proof"),
        ]

    def getDonaldBonusList():
        return [
            KH2Bonus(42,2,locationTypes=[locationType.Agrabah],description="Abu Escort"),
            KH2Bonus(45,2,locationTypes=[locationType.SP],description="Screens"),
            KH2Bonus(28, 2, locationTypes=[locationType.HB], description="Demyx (Hollow Bastion)"),
            KH2Bonus(58, 2, locationTypes=[locationType.OC], description="Demyx (Olympus)"),
            KH2Bonus(22, 2, locationTypes=[locationType.PR], description="Grim Reaper 2"),
            KH2Bonus(16, 2, locationTypes=[locationType.DC], description="Boat Pete", doubleReward=True),
            KH2Bonus(17, 2, locationTypes=[locationType.DC], description="Wharf Pete"),
            KH2Bonus(18, 2, locationTypes=[locationType.HT], description="Prison Keeper"),
            KH2Bonus(29, 2, locationTypes=[locationType.PL], description="Scar"),
            KH2Bonus(61, 2, locationTypes=[locationType.SP], description="Solar Sailor"),
            KH2Bonus(20, 2, locationTypes=[locationType.HT], description="Experiment"),
            KH2Bonus(62, 2, locationTypes=[locationType.PR], description="Boat Fight"),
            KH2Bonus(56,2,locationTypes=[locationType.TT], description="Mansion"),
            KH2Bonus(2, 2, locationTypes=[locationType.BC], description="Posessor"),
            KH2Bonus(4,2,locationTypes=[locationType.BC], description="Xaldin"),
        ]

    def getDonaldWeaponList():
        return [
            KH2ItemStat(151,13,3, Name="Centurion+"),
            KH2ItemStat(90,2,2, Name="Nobody Lance"),
            KH2ItemStat(87,2,1, Name="Hammer Staff"),
            KH2ItemStat(91,3,3,  Name="Lord's Broom"),
            KH2ItemStat(86,1,1,  Name="Mage's Staff"),
            KH2ItemStat(89,4,3, Name="Meteor Staff"),
            KH2ItemStat(94,5,5, Name="Nobody Lance"),
            KH2ItemStat(154,1,5, Name="Precious Mushroom"),
            KH2ItemStat(155,2,7, Name="Precious Mushroom+"),
            KH2ItemStat(156,3,9, Name="Premium Mushroom"),
            KH2ItemStat(93,4,4, Name="Rising Dragon"),
            KH2ItemStat(146,5,6, Name="Save the Queen+"),
            KH2ItemStat(95,4,5, Name="Shaman's Relic"),
            KH2ItemStat(88,3,2,  Name="Victory Bell"),
            KH2ItemStat(92,4,5, Name="Wisdom Wand"),
        ]

    def getDonaldStartingItemList():
        donaldStartingItem = KH2StartingItem(2,0, LocationTypes=[locationType.Free], ArmorSlotMax=1, AccessorySlotMax=2, ItemSlotMax=2)
        donaldStartingItem.setReward(1, equipped=True)
        donaldStartingItem.setReward(3, equipped=True)
        return [donaldStartingItem, donaldStartingItem]

    def getGoofyBonusList():
        return [
            KH2Bonus(21,3,locationTypes=[locationType.PR], description="Barbossa", doubleReward=True),
            KH2Bonus(59,3,locationTypes=[locationType.PR], description="Grim Reaper 1"),
            KH2Bonus(31,3,locationTypes=[locationType.SP], description="Hostile Program"),
            KH2Bonus(49,3,locationTypes=[locationType.PL], description="Hyenas 1"),
            KH2Bonus(50,3,locationTypes=[locationType.PL], description="Hyenas 2"),
            KH2Bonus(40,3,locationTypes=[locationType.HT], description="Lock/Shock/Barrel"),
            KH2Bonus(19, 3, locationTypes=[locationType.HT], description="Oogie Boogie"),
            KH2Bonus(6,3,locationTypes=[locationType.OC], description="Pete (Olympus)"),
            KH2Bonus(17,3,locationTypes=[locationType.DC], description="Pete (Wharf)"),
            KH2Bonus(9,3,locationTypes=[locationType.LoD], description="Shan-Yu"),
            KH2Bonus(10, 3, locationTypes=[locationType.LoD], description="Storm Rider"),
            KH2Bonus(12,3,locationTypes=[locationType.BC], description="Beast"),
            KH2Bonus(39,3,locationTypes=[locationType.PR], description="Interceptor Barrels"),
            KH2Bonus(46,3,locationTypes=[locationType.Agrabah], description="Treasure Room Heartless"),
            KH2Bonus(66,3,locationTypes=[locationType.OC, locationType.AS], description="Zexion"),
        ]

    def getGoofyWeaponList():
        return [
            KH2ItemStat(100,2,0, Name="Adamant Shield"),
            KH2ItemStat(107,7,0, Name="Akashic Record"),
            KH2ItemStat(101,3,0, Name="Chain Gear"),
            KH2ItemStat(104,4,0, Name="Dream Cloud"),
            KH2ItemStat(103,3,0, Name="Falling Star"),
            KH2ItemStat(158,5,0, Name="Frozen Pride+"),
            KH2ItemStat(106,6,0, Name="Genji Shield"),
            KH2ItemStat(105,7,0, Name="Knight Defender"),
            KH2ItemStat(99,1,0, Name="Knight's Shield"),
            KH2ItemStat(161,5,0, Name="Majestic Mushroom"),
            KH2ItemStat(162,7,0, Name="Majestic Mushroom+"),
            KH2ItemStat(108,8,0, Name="Nobody Guard"),
            KH2ItemStat(102,5,0, Name="Ogre Shield"),
            KH2ItemStat(147,9,0, Name="Save The King+"),
            KH2ItemStat(163,9,0, Name="Ultimate Mushroom"), 
        ]

    def getGoofyStartingItemList():
        goofyStartingItem = KH2StartingItem(3,0, LocationTypes=[locationType.Free], ArmorSlotMax=2, AccessorySlotMax=1, ItemSlotMax=3)
        goofyStartingItem.setReward(1, equipped=True)
        goofyStartingItem.setReward(1, equipped=True)
        goofyStartingItem.setReward(1, equipped=True)
        return [goofyStartingItem, goofyStartingItem]

    def getAdditionalGoofy(count):
        return random.shuffle([
            (KH2ItemStat(0,7,0, Name="Akashic Record +"), KH2Item(601, Name="Akashic Record +", ItemType=itemType.SHIELD)),
            (KH2ItemStat(0,1,0, Name="Joyous Mushroom"), KH2Item(554, Name="Joyous Mushroom", ItemType=itemType.SHIELD)),
            (KH2ItemStat(0,3,0, Name="Joyous Mushroom +"), KH2Item(555, Name="Joyous Mushroom +", ItemType=itemType.SHIELD)),
            (KH2ItemStat(0,5,0, Name="Frozen Pride"), KH2Item(552, Name="Frozen Pride", ItemType=itemType.SHIELD)),
            (KH2ItemStat(0,7,0, Name="Save the King"), KH2Item(483, Name="Save the King", ItemType=itemType.SHIELD)),
        ])[:count]

    def getAdditionalDonald(count):
        return random.shuffle([
            (KH2ItemStat(0,0,0, Name=""), KH2Item(0, Name="", ItemType=itemType.STAFF)),
            (KH2ItemStat(0,0,0, Name=""), KH2Item(0, Name="", ItemType=itemType.STAFF))

        ])[:count]

def getOptions():
    return [
        {
            "Worlds (Chests, Bonus Levels, Rewards)": [
                locationType.LoD,
                locationType.BC,
                locationType.HB,
                locationType.CoR,
                locationType.TT,
                locationType.TWTNW,
                locationType.SP,
                locationType.Atlantica,
                locationType.PR,
                locationType.OC,

                locationType.Agrabah,
                locationType.HT,
                locationType.PL,
                locationType.DC,
                locationType.HUNDREDAW,
                locationType.STT,
            ]},
            {"Superboss Rewards": [
                locationType.AS,
                locationType.Sephi,
                locationType.LW,
                locationType.DataOrg,
            ]},
            {"Misc Rewards":[
                locationType.OCCups,
                locationType.OCParadoxCup,
                locationType.FormLevel,
                locationType.Free,
                locationType.Critical,
            ]}

    ]


# lionStartWithDash = KH2StartingItem(135, 0, Hp=0, Ap=0, Mp=0, Unknown06=0, Unknown08 = 0, Unknown0a = 0)
# lionStartWithDash.setReward(-32606)
# lionStartWithDash.setReward(-32606)
# lionStartWithDash.setReward(-32605)
# lionStartWithDash.setReward(-32605)
# lionStartWithDash.setReward(-32248)
# lionStartWithDash.setReward(-32247)
# lionStartWithDash.setReward(-32246)
# lionStartWithDash.setReward(-32242)
