Program 0x99
Bgm 134 134
AreaSettings 7 -1
	SetProgressFlag 0x8A6
	SetUnk05 0x3
	SetEvent "804" Type 8
	SetJump Type 1 World TT Area 30 Entrance 50 LocalSet 0 FadeType 1
	SetPartyMenu 0


Program 0x00
Spawn "e_50"

Program 0x02
Party DEFAULT
AreaSettings 1 -1
	SetProgressFlag 0x8FA
	SetPartyMenu 0

Spawn "e_50"

Program 0x155
Bgm Default Default
AreaSettings 0 -1
	SetEvent "804" Type 66
	SetJump Type 2 World TT Area 0 Entrance 0 LocalSet 342 FadeType 1
	SetPartyMenu 0
