Program 0x0A
Capacity 9.1E-44
StatusFlag3
Spawn "b_80"
Spawn "b_20"

Program 0x68
Capacity 8.4E-44
Party NO_FRIEND
StatusFlag3
Mission 0x5C "MU08_MS107"
Spawn "z_40"

Program 0x51
Progress 0x2018
Party W_FRIEND
Mission 0x5F "MU08_MS202"
Spawn "b_60"

Program 0x01
Capacity 6.7E-44
Spawn "b_00"
Spawn "b_80"

Program 0x4F
Progress 0x2018
Party W_FRIEND
Mission 0x18 "MU08_MS204"
Spawn "b_61"
Spawn "b_70"

Program 0x4A
Progress 0x2018
Party W_FRIEND
Mission 0x5C "MU08_MS107"
Spawn "b_40"