Program 0x3C
Mission 0x38 "PO09_MS400"
Spawn "b_41"

Program 0x3D
Capacity 7.7E-44
Mission 0x39 "PO09_MS401"
Spawn "b_99"
Spawn "b_10"
Spawn "b_30"
Spawn "b_41"

Program 0x19
Spawn "b_40"

Program 0x4A
MsgWall 0x8599
MapVisibility 0x00000005 0x00000000
Mission 0x39 "PO09_MS401"
Spawn "b_99"
Spawn "b_10"
Spawn "b_30"
Spawn "b_41"
Spawn "m_10"
Spawn "m_50"
Spawn "m_70"

Program 0x48
Capacity 7.7E-44
Mission 0x102 "PO09_MS401_FREE"
Spawn "b_99"
Spawn "b_10"
Spawn "b_30"
Spawn "b_41"