Program 0x0A
Capacity 8.4E-44
Unk06 0
Party W_FRIEND
StatusFlag3
Mission 0xE1 "SHIP_BATTLE"
Spawn "b_20"

Program 0x0B
Capacity 8.4E-44
Unk06 0
Party W_FRIEND
StatusFlag3
Mission 0xE1 "SHIP_BATTLE"
Spawn "b_21"

Program 0x0C
Capacity 8.4E-44
Unk06 0
Party W_FRIEND
StatusFlag3
Mission 0xE1 "SHIP_BATTLE"
CasualSpawn 30 "b_30"
Spawn "b_22"

Program 0x01
Capacity 6.4E-44
Unk06 0
Party W_FRIEND
StatusFlag3
Mission 0xE1 "SHIP_BATTLE"
Spawn "b_03"