Program 0x0A
AreaSettings 7 -1
	SetProgressFlag 0x4047
	SetUnk05 0x3
	SetJump Type 1 World CA Area 5 Entrance 0 LocalSet 0 FadeType 16385
	SetPartyMenu 0


Program 0x0B
AreaSettings 7 -1
	SetUnk05 0x3
	SetJump Type 1 World CA Area 16 Entrance 1 LocalSet 0 FadeType 16385
	SetPartyMenu 0


Program 0x01
AreaSettings 7 -1
	SetUnk05 0x3
	SetJump Type 1 World CA Area 16 Entrance 1 LocalSet 0 FadeType 16385
	SetPartyMenu 0
