Program 0x01
AreaSettings 7 -1
	SetUnk05 0x3
	SetJump Type 1 World CA Area 1 Entrance 2 LocalSet 0 FadeType 16385
	SetPartyMenu 0


Program 0x02
AreaSettings 7 -1
	SetProgressFlag 0x4045
	SetUnk05 0x3
	SetJump Type 1 World CA Area 4 Entrance 0 LocalSet 0 FadeType 16385
	SetPartyMenu 0


Program 0x04
AreaSettings 7 -1
	SetUnk05 0x3
	SetJump Type 1 World CA Area 1 Entrance 2 LocalSet 0 FadeType 16385
	SetPartyMenu 0
