Program 0x15
Spawn "d21_"

Program 0x16
Spawn "d10_"

Program 0x00


Program 0x01
Bgm 129 129
AreaSettings 0 -1
	SetProgressFlag 0x2C0E
	SetEvent "204" Type 2
	SetJump Type 1 World LM Area 2 Entrance 0 LocalSet 0 FadeType 1
	SetPartyMenu 0


Program 0x0D
Spawn "d50_"

Program 0x0E
Spawn "d41_"

Program 0x0F
Spawn "d40_"

Program 0x10
Spawn "d30_"

Program 0x11
Spawn "d20_"

Program 0x12
Spawn "d51_"

Program 0x13
Spawn "d42_"

Program 0x14
Spawn "d31_"