Program 0x0A
Capacity 8.4E-44
Unk06 0
Party W_FRIEND
StatusFlag3
Mission 0xE1 "SHIP_BATTLE"
Spawn "b_00"

Program 0x0B
Capacity 8.4E-44
Unk06 0
Party W_FRIEND
StatusFlag3
Mission 0xE1 "SHIP_BATTLE"
CasualSpawn 30 "b_30"
Spawn "b_01"

Program 0x01
Capacity 6.4E-44
Unk06 0
Party W_FRIEND
StatusFlag3
Mission 0xE1 "SHIP_BATTLE"
Spawn "b_03"

Program 0x55
Progress 0x4061
Unk06 0
Party W_FRIEND
Mission 0x12C "CA18_MS202"
Spawn "b_60"