Program 0x0A
AreaSettings 7 -1
	SetUnk05 0x3
	SetJump Type 1 World CA Area 1 Entrance 2 LocalSet 0 FadeType 16385
	SetPartyMenu 0


Program 0x01
AreaSettings 7 -1
	SetUnk05 0x3
	SetJump Type 1 World CA Area 1 Entrance 2 LocalSet 0 FadeType 16385
	SetPartyMenu 0


Program 0x55
Bgm 111 111
AreaSettings 16 -1
	SetProgressFlag 0x4062
	SetUnk05 0x3
	SetJump Type 2 World CA Area 0 Entrance 0 LocalSet 86 FadeType 16386
	SetPartyMenu 0
